int w2=act(win("Untitled - Paint" "MSPaintApp"))
BlockInput 1
lef+ 92 138 w2
 mou "A@A@A@A@CAB@DAD@GAFAIAF@GAGBF@HAGAHAHAI@JAJ@JAHAGAFAGBHAHAI@H@HAH@GBGAIAGBEBFAD@EACBA@BAA@@AbAcBcAfAgAh@ibjaiahbd@a@AACBFDGCFDFCEABA@Aa@badag@iahagac@b@BADDFDGEFDBB@Ab@e@iblakag@c@@ABADDCBCC@AcAeAiBiAhBdBb@@A@ABBEDFEFEDDBAbAd@i@k@j@g@dAb@@A@A@C@BaAb@cBeCcCgDdEhGgGfJcKaL@KANDPLZJRHRCLCHCHBECFDFCFEDDBGAJ@LcPg+30-18+28-24UwLoHhEfBeAg@jelgkghgceadAeEaG@HEJIFKGMDOAOcRhNjIlGgDeDeCdBeAfBjBl@nclcmehegacAbEbGbGbHaHbJaJaIaIaI@L@NANAKAHAEAB@A@@bAc@c@d@cAcBcCeAcCcCbBbCaDaCaD@E@GAFBFADACABAB@B@B@A@BA"
 mou "BABAA@BBBBBBCCCBDDBCBBaBbBcDhGkJtQ-29+25-38+31-45+36-44+36-44+38-42+36-25+33nVeLaH@GDFHEHFICHBG@GaEbFaCaBaA@AaDaEaHaKaMbObL@IbG@E@D@B@A@A@B@B@B@C@FBHAHAI@GAGAFCGCFEDHCGAGACABA@A@A@@AA@AACABBCADBE@C@CbCaCaA@A@@a@a@aabacbfek-14-27-30-51-49-72-61-82-65-71-47-41-27-21qlgfaaDbC@B@AaAaAaAaAbCaBbEcDbFbHbLcMdMcLcKaI@GaB@A@A@BABACBFCIDICJEIBGBD@C@A@BbA@BbCaB@B@B@B@C@C@F@D@A@bAcBeCdBeCfBeAgBjClDmElDkEhDiChCjDhCiDhEfDeDcDbAcCcBcBdCdCfCgAhAk@mbpdrdpclbkahad@b@a@a@bafbiemgohlelcjagBcBbE@E@GEGDFEFFGFD"
 mou "EDDEABc@dbgbkal@lBhCgCcB@C@CEFHHJJLLJJFFBDbAfCoGtGnFjGdDbC@CCDIILKTQNLIIBDbAgCpEvEpEkEeD@BACEFKLNOQTKLEHABbBcDeDdFaE@CCEFDIDKDKDMBKBJ@IbGbEaHeHfIhHkJv+6-30Coafcbaaa@b@aC@F@L@NBODKFIGGJFKFNEMAL@KAH@GAG@F@GaIfIhJkMkKeGbDaB@A@ABBEAGCICKFMHJJGIELEKFKENENEMAO@MdLeIgGjDhBcA@B@A@BBCDEFEGHIHIHHIEHDFAFaDdFfEjCn@p@p@l@h@hbjahaicibhcjdgdgdfdfcdbc@b@bAeDfDgCgEgDhDgBfBdAf@d@eagdgdfehfgefbb@aAbBaBcAaAaAa@a@a"
mou "+20-0x@"
lef- 700 343 w2
