type TESTTYPE0 str'a BSTR'b x y POINT'p
type TESTTYPE1 str'a BSTR'b x y POINT'p
type TESTTYPE2 str'a BSTR'b x y POINT'p
type TESTTYPE3 str'a BSTR'b x y POINT'p
type TESTTYPE4 str'a BSTR'b x y POINT'p
type TESTTYPE5 str'a BSTR'b x y POINT'p
type TESTTYPE6 str'a BSTR'b x y POINT'p
type TESTTYPE7 str'a BSTR'b x y POINT'p
type TESTTYPE8 str'a BSTR'b x y POINT'p
type TESTTYPE9 str'a BSTR'b x y POINT'p
type TESTTYPE10 str'a BSTR'b x y POINT'p
type TESTTYPE11 str'a BSTR'b x y POINT'p
type TESTTYPE12 str'a BSTR'b x y POINT'p
type TESTTYPE13 str'a BSTR'b x y POINT'p
type TESTTYPE14 str'a BSTR'b x y POINT'p
type TESTTYPE15 str'a BSTR'b x y POINT'p
type TESTTYPE16 str'a BSTR'b x y POINT'p
type TESTTYPE17 str'a BSTR'b x y POINT'p
type TESTTYPE18 str'a BSTR'b x y POINT'p
type TESTTYPE19 str'a BSTR'b x y POINT'p
type TESTTYPE20 str'a BSTR'b x y POINT'p
type TESTTYPE21 str'a BSTR'b x y POINT'p
type TESTTYPE22 str'a BSTR'b x y POINT'p
type TESTTYPE23 str'a BSTR'b x y POINT'p
type TESTTYPE24 str'a BSTR'b x y POINT'p
type TESTTYPE25 str'a BSTR'b x y POINT'p
type TESTTYPE26 str'a BSTR'b x y POINT'p
type TESTTYPE27 str'a BSTR'b x y POINT'p
type TESTTYPE28 str'a BSTR'b x y POINT'p
type TESTTYPE29 str'a BSTR'b x y POINT'p
type TESTTYPE30 str'a BSTR'b x y POINT'p
type TESTTYPE31 str'a BSTR'b x y POINT'p
type TESTTYPE32 str'a BSTR'b x y POINT'p
type TESTTYPE33 str'a BSTR'b x y POINT'p
type TESTTYPE34 str'a BSTR'b x y POINT'p
type TESTTYPE35 str'a BSTR'b x y POINT'p
type TESTTYPE36 str'a BSTR'b x y POINT'p
type TESTTYPE37 str'a BSTR'b x y POINT'p
type TESTTYPE38 str'a BSTR'b x y POINT'p
type TESTTYPE39 str'a BSTR'b x y POINT'p
type TESTTYPE40 str'a BSTR'b x y POINT'p
type TESTTYPE41 str'a BSTR'b x y POINT'p
type TESTTYPE42 str'a BSTR'b x y POINT'p
type TESTTYPE43 str'a BSTR'b x y POINT'p
type TESTTYPE44 str'a BSTR'b x y POINT'p
type TESTTYPE45 str'a BSTR'b x y POINT'p
type TESTTYPE46 str'a BSTR'b x y POINT'p
type TESTTYPE47 str'a BSTR'b x y POINT'p
type TESTTYPE48 str'a BSTR'b x y POINT'p
type TESTTYPE49 str'a BSTR'b x y POINT'p
type TESTTYPE50 str'a BSTR'b x y POINT'p
type TESTTYPE51 str'a BSTR'b x y POINT'p
type TESTTYPE52 str'a BSTR'b x y POINT'p
type TESTTYPE53 str'a BSTR'b x y POINT'p
type TESTTYPE54 str'a BSTR'b x y POINT'p
type TESTTYPE55 str'a BSTR'b x y POINT'p
type TESTTYPE56 str'a BSTR'b x y POINT'p
type TESTTYPE57 str'a BSTR'b x y POINT'p
type TESTTYPE58 str'a BSTR'b x y POINT'p
type TESTTYPE59 str'a BSTR'b x y POINT'p
