/b/i/c/p3
zkey :'"zyyyyyyyyyy"
zpas :"zuuuuuuuuuu"
zkey2 :'"zyyy" V "zyyy"; '"zyyy"
zpas2 :"zuuu"; " uuuuuuu"
zkey3 :Function193 "zyyyyyyyyyy"
zpas3 :Function193 "zyyyyyyyyyy" 1
zky :"on zky"
xy :'"xxxxxx"
x[65]B :"kkkk"
moo :"not in notepad"
com :outTsmTrigger
a123 :"numberA"
b123 :"numberB"
zkey2 :'"zyyyyyyyyyy" (1.0) "aaa"
cc\ :'"delim last"
d\d :'"delim in"
\cc :'"delim first"
/b/i/c
ee\ :'"delim last 2"
fff :'"no delim"
ee.. :'"delim last 3"
.gg :'"delim first"
tt[9] :'"tab"
pp[] :'"enter"
o[]o[]o :'"enter"
spa  :'"space"
