interface# ISelenium :IUnknown
	SetExtensionJs(BSTR'extensionJs)
	Start()
	Stop()
	Click(BSTR'locator)
	DoubleClick(BSTR'locator)
	ContextMenu(BSTR'locator)
	ClickAt(BSTR'locator BSTR'coordString)
	DoubleClickAt(BSTR'locator BSTR'coordString)
	ContextMenuAt(BSTR'locator BSTR'coordString)
	FireEvent(BSTR'locator BSTR'eventName)
	Focus(BSTR'locator)
	KeyPress(BSTR'locator BSTR'keySequence)
	ShiftKeyDown()
	ShiftKeyUp()
	MetaKeyDown()
	MetaKeyUp()
	AltKeyDown()
	AltKeyUp()
	ControlKeyDown()
	ControlKeyUp()
	KeyDown(BSTR'locator BSTR'keySequence)
	KeyUp(BSTR'locator BSTR'keySequence)
	MouseOver(BSTR'locator)
	MouseOut(BSTR'locator)
	MouseDown(BSTR'locator)
	MouseDownRight(BSTR'locator)
	MouseDownAt(BSTR'locator BSTR'coordString)
	MouseDownRightAt(BSTR'locator BSTR'coordString)
	MouseUp(BSTR'locator)
	MouseUpRight(BSTR'locator)
	MouseUpAt(BSTR'locator BSTR'coordString)
	MouseUpRightAt(BSTR'locator BSTR'coordString)
	MouseMove(BSTR'locator)
	MouseMoveAt(BSTR'locator BSTR'coordString)
	Type(BSTR'locator BSTR'value)
	TypeKeys(BSTR'locator BSTR'value)
	SetSpeed(BSTR'value)
	BSTR'GetSpeed()
	Check(BSTR'locator)
	Uncheck(BSTR'locator)
	Select(BSTR'selectLocator BSTR'optionLocator)
	AddSelection(BSTR'locator BSTR'optionLocator)
	RemoveSelection(BSTR'locator BSTR'optionLocator)
	RemoveAllSelections(BSTR'locator)
	Submit(BSTR'formLocator)
	Open(BSTR'url)
	OpenWindow(BSTR'url BSTR'windowID)
	SelectWindow(BSTR'windowID)
	SelectPopUp(BSTR'windowID)
	DeselectPopUp()
	SelectFrame(BSTR'locator)
	@GetWhetherThisFrameMatchFrameExpression(BSTR'currentFrameString BSTR'target)
	@GetWhetherThisWindowMatchWindowExpression(BSTR'currentWindowString BSTR'target)
	WaitForPopUp(BSTR'windowID BSTR'timeout)
	ChooseCancelOnNextConfirmation()
	ChooseOkOnNextConfirmation()
	AnswerOnNextPrompt(BSTR'answer)
	GoBack()
	Refresh()
	Close()
	@IsAlertPresent()
	@IsPromptPresent()
	@IsConfirmationPresent()
	BSTR'GetAlert()
	BSTR'GetConfirmation()
	BSTR'GetPrompt()
	BSTR'GetLocation()
	BSTR'GetTitle()
	BSTR'GetBodyText()
	BSTR'GetValue(BSTR'locator)
	BSTR'GetText(BSTR'locator)
	Highlight(BSTR'locator)
	BSTR'GetEval(BSTR'script)
	@IsChecked(BSTR'locator)
	BSTR'GetTable(BSTR'tableCellAddress)
	ARRAY(BSTR)GetSelectedLabels(BSTR'selectLocator)
	BSTR'GetSelectedLabel(BSTR'selectLocator)
	ARRAY(BSTR)GetSelectedValues(BSTR'selectLocator)
	BSTR'GetSelectedValue(BSTR'selectLocator)
	ARRAY(BSTR)GetSelectedIndexes(BSTR'selectLocator)
	BSTR'GetSelectedIndex(BSTR'selectLocator)
	ARRAY(BSTR)GetSelectedIds(BSTR'selectLocator)
	BSTR'GetSelectedId(BSTR'selectLocator)
	@IsSomethingSelected(BSTR'selectLocator)
	ARRAY(BSTR)GetSelectOptions(BSTR'selectLocator)
	BSTR'GetAttribute(BSTR'attributeLocator)
	@IsTextPresent(BSTR'pattern)
	@IsElementPresent(BSTR'locator)
	@IsVisible(BSTR'locator)
	@IsEditable(BSTR'locator)
	ARRAY(BSTR)GetAllButtons()
	ARRAY(BSTR)GetAllLinks()
	ARRAY(BSTR)GetAllFields()
	ARRAY(BSTR)GetAttributeFromAllWindows(BSTR'attributeName)
	Dragdrop(BSTR'locator BSTR'movementsString)
	SetMouseSpeed(BSTR'pixels)
	DECIMAL'GetMouseSpeed()
	DragAndDrop(BSTR'locator BSTR'movementsString)
	DragAndDropToObject(BSTR'locatorOfObjectToBeDragged BSTR'locatorOfDragDestinationObject)
	WindowFocus()
	WindowMaximize()
	ARRAY(BSTR)GetAllWindowIds()
	ARRAY(BSTR)GetAllWindowNames()
	ARRAY(BSTR)GetAllWindowTitles()
	BSTR'GetHtmlSource()
	SetCursorPosition(BSTR'locator BSTR'position)
	DECIMAL'GetElementIndex(BSTR'locator)
	@IsOrdered(BSTR'locator1 BSTR'locator2)
	DECIMAL'GetElementPositionLeft(BSTR'locator)
	DECIMAL'GetElementPositionTop(BSTR'locator)
	DECIMAL'GetElementWidth(BSTR'locator)
	DECIMAL'GetElementHeight(BSTR'locator)
	DECIMAL'GetCursorPosition(BSTR'locator)
	BSTR'GetExpression(BSTR'expression)
	DECIMAL'GetXpathCount(BSTR'xpath)
	DECIMAL'GetCSSCount(BSTR'cssLocator)
	AssignId(BSTR'locator BSTR'identifier)
	AllowNativeXpath(BSTR'allow)
	IgnoreAttributesWithoutValue(BSTR'ignore)
	WaitForCondition(BSTR'script BSTR'timeout)
	SetTimeout(BSTR'timeout)
	WaitForPageToLoad(BSTR'timeout)
	WaitForFrameToLoad(BSTR'frameAddress BSTR'timeout)
	BSTR'GetCookie()
	BSTR'GetCookieByName(BSTR'name)
	@IsCookiePresent(BSTR'name)
	CreateCookie(BSTR'nameValuePair BSTR'optionsString)
	DeleteCookie(BSTR'name BSTR'optionsString)
	DeleteAllVisibleCookies()
	SetBrowserLogLevel(BSTR'logLevel)
	RunScript(BSTR'script)
	AddLocationStrategy(BSTR'strategyName BSTR'functionDefinition)
	CaptureEntirePageScreenshot(BSTR'filename BSTR'kwargs)
	Rollup(BSTR'rollupName BSTR'kwargs)
	AddScript(BSTR'scriptContent BSTR'scriptTagId)
	RemoveScript(BSTR'scriptTagId)
	UseXpathLibrary(BSTR'libraryName)
	SetContext(BSTR'context)
	AttachFile(BSTR'fieldLocator BSTR'fileLocator)
	CaptureScreenshot(BSTR'filename)
	BSTR'CaptureScreenshotToString()
	BSTR'CaptureEntirePageScreenshotToString(BSTR'kwargs)
	ShutDownSeleniumServer()
	BSTR'RetrieveLastRemoteControlLogs()
	KeyDownNative(BSTR'keycode)
	KeyUpNative(BSTR'keycode)
	KeyPressNative(BSTR'keycode)
