int w1=win("Dialog1" "#32770")
int w2=win("Dialog2" "#32770")
 Zorder w1 HWND_TOPMOST
SetWindowPos w1 HWND_TOPMOST 0 0 0 0 SWP_NOSIZE|SWP_NOMOVE
 SetWindowPos w2 HWND_TOPMOST 0 0 0 0 SWP_NOSIZE|SWP_NOMOVE
 SetWindowPos w2 HWND_TOPMOST 0 0 0 0 SWP_NOSIZE|SWP_NOMOVE|SWP_NOOWNERZORDER
 ret
1
 rep 2
	  SetWindowPos w2 HWND_NOTOPMOST 0 0 0 0 SWP_NOSIZE|SWP_NOMOVE|SWP_NOACTIVATE
	  SetWindowPos w2 HWND_NOTOPMOST 0 0 0 0 SWP_NOSIZE|SWP_NOMOVE|SWP_NOOWNERZORDER
	 SetWindowPos w2 HWND_NOTOPMOST 0 0 0 0 SWP_NOSIZE|SWP_NOMOVE|SWP_NOACTIVATE|SWP_NOOWNERZORDER
rep 1
	 SetWindowPos w2 HWND_NOTOPMOST 0 0 0 0 SWP_NOSIZE|SWP_NOMOVE|SWP_NOACTIVATE
	 SetWindowPos w2 HWND_NOTOPMOST 0 0 0 0 SWP_NOSIZE|SWP_NOMOVE|SWP_NOOWNERZORDER
	 SetWindowPos w2 HWND_NOTOPMOST 0 0 0 0 SWP_NOSIZE|SWP_NOMOVE|SWP_NOACTIVATE|SWP_NOOWNERZORDER
	SetWindowPos w1 HWND_BOTTOM 0 0 0 0 SWP_NOSIZE|SWP_NOMOVE|SWP_NOACTIVATE
