dll "qm.exe" $FileExistsEx $path [flags]

out
 out FileExistsEx("Q:/app/winapi.txt" 0)
 out FileExistsEx("Q:/app/winapi.txt" 1)
 out FileExistsEx("Q:/app/winapi.txt" 2)
 out FileExistsEx("Q:/app/qmcore" 0)
 out FileExistsEx("Q:/app/qmcore" 1)
 out FileExistsEx("Q:/app/qmcore" 2)
 out FileExistsEx("Q:/app/*.txt" 0)
 out FileExistsEx("Q:/app/*.txt" 1)
 out FileExistsEx("Q:/app/*.txt" 2)
 out FileExistsEx("Q:/app/*" 1)
 out FileExistsEx("$qm$/winapi.txt" 0)
 out FileExistsEx("$qm$/winapi.txt" 0x100)
 out FileExistsEx("$qm$/*.txt" 0x100)
 out FileExistsEx("$qm$/*.txt" 0x100|0x10000000)
out FileExistsEx("Q:/app/*a*" 0)
out FileExistsEx("Q:/app/*a*" 1)
out FileExistsEx("Q:/app/*a*" 2)
