outp _s.getmacro("TO_CBGetItem")
key (_s.getmacro("???"))
_s.getmacro("???")
out _s.getmacro("???")
str j.getmacro("???")
_s.getmacro("???"); _s.setclip()
_s.getmacro("???"); _s.setwintext(h)
ShowText("" _s.getmacro("???"))
_s.getmacro("init"); _s.setfile("C:\Documents and Settings\G\Desktop\led.txt")
HtmlSetText(_s.getmacro("Dialog_Editor") "TD" "Includes the heap list of the specified process in the snapshot." "" "MSDN Library - January 2002 - CreateToolhelp32Snapshot" 0 9 0x21)

outp _s.getfile("C:\Documents and Settings\G\Desktop\led.txt")
key (_s.getfile("C:\Documents and Settings\G\Desktop\led.txt"))
_s.getfile("C:\Documents and Settings\G\Desktop\led.txt")
str k.getfile("C:\Documents and Settings\G\Desktop\led.txt")
_s.getfile("???"); _s.setclip()
ShowText("" _s.getfile("???"))
_s.getfile("???"); _s.setwintext(id(1001 "MSDN Library - January 2002 - CreateToolhelp32Snapshot"))
_s.getfile("???"); _s.setfile("$History$\k")

key Cv
key (_s.getclip())
out _s.getclip()
_s.getclip()
_s.getclip(); _s.setclip()
ShowText("" _s.getclip())
_s.getclip(); _s.setwintext(h)
a.SetValue(_s.getclip())
_s.getclip(); _s.setfile("???")
LogFile(_s.getclip() 1)
k=_s.getclip()
el.innerText=_s.getclip()
op7^.innerText=_s.getclip()
