Acc a=acc("Desktop" "LIST" "Program Manager" "SysListView32" "" 0x1001)
a.SetValue("")
a=acc("Desktop" "LIST" "Program Manager" "SysListView32" "" 0x1001)
a.SetValue("")
Acc n78_Q=acc("Desktop" "LIST" "Program Manager" "SysListView32" "" 0x1001)
n78_Q.SetValue("")
sd.SetValue(u)
a.SetValue("")

el.SetText("")
oo.SetText("")
Htm el=htm("IMG" "pagerrorImg" "" " Internet Explorer" 0 0 0x121)
el.SetText("")
MSHTML.IHTMLElement elem
elem.SetText("")
