 Constants FOR TrID_GetInfo
def TRID_GET_RES_NUM 1
def TRID_GET_RES_FILETYPE 2
def TRID_GET_RES_FILEEXT 3
def TRID_GET_RES_POINTS 4

def TRID_GET_VER 1001
def TRID_GET_DEFSNUM 1004

 Additional constants for the full version
def TRID_GET_DEF_ID 100
def TRID_GET_DEF_FILESCANNED 101
def TRID_GET_DEF_AUTHORNAME 102
def TRID_GET_DEF_AUTHOREMAIL 103
def TRID_GET_DEF_AUTHORHOME 104
def TRID_GET_DEF_FILE 105
def TRID_GET_DEF_REMARK 106
def TRID_GET_DEF_RELURL 107
def TRID_GET_DEF_TAG 108
def TRID_GET_DEF_MIMETYPE 109

def TRID_GET_ISTEXT 1005

 Functions
dll tridlib
	#TrID_LoadDefsPack $sPath
	#TrID_SubmitFileA $sFileName
	#TrID_Analyze
	#TrID_GetInfo lInfoType lInfoIdx $sTrIDRes
