out
out _s.timeformat("text")
out _s.timeformat("")
out _s.timeformat("{D} {T}")
out _s.timeformat("{DD} {TT}")
 out _s.timeformat("beg {DD} {TT}")
 out _s.timeformat("{DD} {TT} end")
 out _s.timeformat("beg {DD}{TT} end")
 out _s.timeformat("{}")
 out _s.timeformat("beg {} end")
 out _s.timeformat("{{}")
 out _s.timeformat("beg {{} end")
 out _s.timeformat("{ k }")
out _s.timeformat("{yyyy MMMM 'gg'}")
out _s.timeformat("{ H.m.s }")
out _s.timeformat("{ H.m.s yMdgg}")
out _s.timeformat("{DD} {TT}" 0 0 DATE_YEARMONTH TIME_FORCE24HOURFORMAT|TIME_NOTIMEMARKER)
out _s.timeformat("{DD} {TT}" 0 LOCALE_USER_DEFAULT)
out _s.timeformat("{DD} {TT}" 0 LANG_RUSSIAN)
out _s.timeformat("{DD} {TT}" 0 LANG_MONGOLIAN)
out _s.timeformat("{DD} {TT}" 0 LANG_MONGOLIAN|(SUBLANG_MONGOLIAN_CYRILLIC_MONGOLIA<<10))
out _s.timeformat("{DD} {TT}" 0 LANG_MONGOLIAN|(SUBLANG_MONGOLIAN_PRC<<10))
out _s.timeformat("{DD} {TT}" 0 LANG_MONGOLIAN|(SUBLANG_MONGOLIAN_PRC<<10) -1 -1); out _hresult ;;fails because of bad flags (ok)
out _s.timeformat("{DD} {TT}" 0 -1) ;;fails but retries with default locale
out _s.timeformat("{y}")
