qm :run "\\gintaras\myprojects\app\qm.exe"
qmcl :run "\\gintaras\myprojects\app\qmcl.exe"
quickmac :run "\\gintaras\myprojects\app\quickmac.exe"
qmvista :run "\\gintaras\myprojects\app\qmvista.exe"
quickm21.~is :run "\\gintaras\myprojects\app\quickm21.~is"
ctoqm.dll :run "\\gintaras\myprojects\app\ctoqm.dll"
App.h :run "\\gintaras\myprojects\app\App.h"
App.cpp :run "\\gintaras\myprojects\app\App.cpp"
hhuser.chm :run "\\gintaras\myprojects\app\hhuser.chm"
blank.htm :web "\\gintaras\myprojects\app\blank.htm"
acc.ico :run "\\gintaras\myprojects\app\acc.ico"
10 - Le Voyage De Penelope.mp3 :run "\\gintaras\F\MP3\Air\10 - Le Voyage De Penelope.mp3"
New AtlTraceTool Trace Settings File.trc :run "\\gintaras\F\test\New AtlTraceTool Trace Settings File.trc"
New Bitmap Image.bmp :run "\\gintaras\F\test\New Bitmap Image.bmp"
New Microsoft Excel Worksheet.xls :run "\\gintaras\F\test\New Microsoft Excel Worksheet.xls"
New Microsoft Office Access Application.mdb :run "\\gintaras\F\test\New Microsoft Office Access Application.mdb"
New Microsoft Office Publisher Document.pub :run "\\gintaras\F\test\New Microsoft Office Publisher Document.pub"
New Microsoft PowerPoint Presentation.ppt :run "\\gintaras\F\test\New Microsoft PowerPoint Presentation.ppt"
New Microsoft Word Document.doc :run "\\gintaras\F\test\New Microsoft Word Document.doc"
