 int i=newitem("" "" "" "" "f2")
 int i=newitem("" "" "" "" "f2new")
 int i=newitem("" "" "" "" "\f11\f2")
 int i=newitem("" "" "" "" "\f1\f22\f3")
 int i=newitem("" "" "" "" "Temp")
 int i=newitem("" "" "" "" "\Temp")
int i=newitem("" "" "" "" "\Tem")
 int i=newitem("" "" "" "" "\Temp\f1\f2")
 int i=newitem("" "" "" "" "\System")
out i
