function#

 Returns target process handle.
 Access rights: PROCESS_VM_OPERATION|PROCESS_VM_READ|PROCESS_VM_WRITE|PROCESS_DUP_HANDLE|SYNCHRONIZE|PROCESS_CREATE_THREAD|PROCESS_QUERY_INFORMATION.

 QM 2.3.3. Added PROCESS_CREATE_THREAD|PROCESS_QUERY_INFORMATION.


ret m_hproc
