 outp _s.getmacro("Macro18")
 key (_s.getmacro("m"))
 _s.getmacro("m")
 str s.getmacro("m")
 _s.getmacro("???"); _s.setclip()
 ShowText("" _s.getmacro("???"))
 _s.getmacro("???"); _s.setwintext(h)
 a.SetValue(_s.getmacro("m"))
 h=_s.getmacro("???")
 _s.getmacro("???"); _s.setfile("f")
 outp _s.getfile("C:\Documents and Settings\a\Desktop\ktest.txt")
 str s.getfile("$Favorites$\ff.html")
 key Cv
 key (_s.getclip())
 out _s.getclip()
 str s.getclip()
 _s.getclip(); _s.setclip()
 _s.getclip(); _s.setfile("C:\Documents and Settings\a\Desktop\test.txt" -1 -1 1)
