 /
function~ status

str s
sel status
	case INTERNET_STATUS_CLOSING_CONNECTION s="INTERNET_STATUS_CLOSING_CONNECTION" 
	case INTERNET_STATUS_CONNECTED_TO_SERVER s="INTERNET_STATUS_CONNECTED_TO_SERVER" 
	case INTERNET_STATUS_CONNECTING_TO_SERVER s="INTERNET_STATUS_CONNECTING_TO_SERVER" 
	case INTERNET_STATUS_CONNECTION_CLOSED s="INTERNET_STATUS_CONNECTION_CLOSED" 
	case INTERNET_STATUS_COOKIE_HISTORY s="INTERNET_STATUS_COOKIE_HISTORY" 
	case INTERNET_STATUS_COOKIE_RECEIVED s="INTERNET_STATUS_COOKIE_RECEIVED" 
	case INTERNET_STATUS_COOKIE_SENT s="INTERNET_STATUS_COOKIE_SENT" 
	case INTERNET_STATUS_CTL_RESPONSE_RECEIVED s="INTERNET_STATUS_CTL_RESPONSE_RECEIVED" 
	case INTERNET_STATUS_DETECTING_PROXY s="INTERNET_STATUS_DETECTING_PROXY" 
	case INTERNET_STATUS_HANDLE_CLOSING s="INTERNET_STATUS_HANDLE_CLOSING" 
	case INTERNET_STATUS_HANDLE_CREATED s="INTERNET_STATUS_HANDLE_CREATED" 
	case INTERNET_STATUS_INTERMEDIATE_RESPONSE s="INTERNET_STATUS_INTERMEDIATE_RESPONSE" 
	case INTERNET_STATUS_NAME_RESOLVED s="INTERNET_STATUS_NAME_RESOLVED" 
	case INTERNET_STATUS_P3P_HEADER s="INTERNET_STATUS_P3P_HEADER" 
	case INTERNET_STATUS_P3P_POLICYREF s="INTERNET_STATUS_P3P_POLICYREF" 
	case INTERNET_STATUS_PREFETCH s="INTERNET_STATUS_PREFETCH" 
	case INTERNET_STATUS_PRIVACY_IMPACTED s="INTERNET_STATUS_PRIVACY_IMPACTED" 
	case INTERNET_STATUS_RECEIVING_RESPONSE s="INTERNET_STATUS_RECEIVING_RESPONSE" 
	case INTERNET_STATUS_REDIRECT s="INTERNET_STATUS_REDIRECT" 
	case INTERNET_STATUS_REQUEST_COMPLETE s="INTERNET_STATUS_REQUEST_COMPLETE" 
	case INTERNET_STATUS_REQUEST_SENT s="INTERNET_STATUS_REQUEST_SENT" 
	case INTERNET_STATUS_RESOLVING_NAME s="INTERNET_STATUS_RESOLVING_NAME" 
	case INTERNET_STATUS_RESPONSE_RECEIVED s="INTERNET_STATUS_RESPONSE_RECEIVED" 
	case INTERNET_STATUS_SENDING_REQUEST s="INTERNET_STATUS_SENDING_REQUEST" 
	case INTERNET_STATUS_STATE_CHANGE s="INTERNET_STATUS_STATE_CHANGE" 

ret s
