00 END0             20 VARSTATIC        40 CAST_INT_FROM_FRIEND      60 
01 USER             21 VARLOCALREF      41 CAST_LONG_FROM_FRIEND     61 
02 DLL              22 VARSTATICREF     42 CAST_DOUBLE_FROM_FRIEND   62 
03 EXPRESSION       23 REF_EQUAL        43 CAST_INTERFACE            63 
04 MINUS            24 EQUALI           44 MINUS_FRIEND              64 
05 INVERT           25 EQUALU           45 INVERT_FRIEND             65 
06 LOGNOT           26 EQUALB           46 LOGNOT_FRIEND             66 
07 CAST_LONG        27 EQUALW           47 CALLCOM                   67 
08 CAST_DOUBLE      28 EQUALL           48 INVOKE                    68 
09 VAL_INT          29 EQUALD           49 DLL4                      69 
0A VAL_UINT         2A OPEQUALI         4A EATRET                    6A 
0B VAL_BYTE         2B OPEQUALU         4B GARBAGE                   6B 
0C VAL_WORD         2C OPEQUALB         4C VARAPPMAIN                6C 
0D VAL_DOUBLE       2D OPEQUALW         4D VARAPPMAINREF             6D 
0E VAL_LONG         2E OPEQUALL         4E VARSUBPARENT              6E 
0F POINTER          2F OPEQUALD         4F VARSUBPARENTREF           6F 
10 POINTER2         30 WAIT             50 VARTHREADSET              70 
11 ADDRESS          31 WAITFOR          51 CAST_POINTER_FROM_FRIEND  71 
12 MEMBER           32 FORE             52 METHOD                    72 
13 MEMBER0          33 FOR2             53 FPTR                      73 
14 MEMBERPTR        34 STR_EQUAL        54 UDF_ADDR                  74 
15 MEMBERPTR0       35 STR_ADD          55 DLL_ADDR                  75 
16 ARRAY            36 STR_SUB          56                           76 
17 BYTEARRAY        37 FSTR             57                           77 
18 STATICARRAY      38 FFRIEND          58                           78 
19 CONSTINT         39 FINTERFACE       59                           79 
1A CONSTUINT        3A FARRAY           5A                           7A ARGSTRUCT
1B CONSTBYTE        3B ARRAY_ELEM       5B                           7B ARGCLASS
1C CONSTDOUBLE      3C STRUCT_EQUAL     5C                           7C ARGFRIEND
1D CONSTLONG        3D STRUCT_EQUAL2    5D                           7D ARGINTERFACE
1E CONSTSTRING      3E INTERFACE_EQUAL  5E                           7E ARGLONG
1F VARLOCAL         3F FRIEND_EQUAL     5F                           7F ARGOPTIONAL

80 act              A0 findc            C0 mou                       E0 type
81 and_kw           A1 findcr           C1 mid                       E1 this
82 atend            A2 findcs           C2 mes                       E2 tok
83 acc              A3 findcn           C3 mkdir                     E3 tim
84 acctest          A4 findw            C4 matchw                    E4 typelib
85 bee              A5 findt            C5 numlines                  E5 uuidof
86 break            A6 findl            C6 newitem                   E6 val
87 but              A7 findb            C7 net                       E7 win
88 case             A8 findrx           C8 opt                       E8 wintest
89 continue         A9 goto             C9 out                       E9 wait_kw
8A clo              AA getopt           CA or_kw                     EA web
8B cop              AB hid              CB ont                       EB xm
8C child            AC htm              CC paste                     EC ym
8D childtest        AD if               CD pixel                     ED zip
8E call             AE ifk              CE perf                      EE __test
8F class            AF iff              CF qmitem                    EF 
90 category         B0 ifa              D0 ret                       F0 
91 dll_keyword      B1 ifi              D1 rep                       F1 
92 def              B2 iif              D2 ren                       F2 
93 dou              B3 inp              D3 res                       F3 
94 dis              B4 id               D4 rig                       F4 
95 del              B5 interface        D5 run                       F5 
96 dir              B6 inpp             D6 rget                      F6 
97 deb              B7 key              D7 rset                      F7 
98 else             B8 lef              D8 ref                       F8 
99 err              B9 lock             D9 sel                       F9 
9A end              BA len              DA spe                       FA 
9B empty            BB mac              DB siz                       FB 
9C for              BC min              DC sizeof                    FC 
9D foreach          BD max              DD share                     FD 
9E function         BE men              DE shutdown                  FE 
9F find             BF mov              DF scan                      FF 

Generated by CodeByteToStr() (qm test functions.cpp).
