int+ _he=0;
 _he=SetWinEventHook(EVENT_MIN, EVENT_MAX, 0, &WinEventProc, 0, 0, WINEVENT_OUTOFCONTEXT|WINEVENT_SKIPOWNPROCESS);
_he=SetWinEventHook(EVENT_OBJECT_DESTROY, EVENT_OBJECT_DESTROY, 0, &WinEventProc, 0, 0, WINEVENT_OUTOFCONTEXT|WINEVENT_SKIPOWNPROCESS);
mes ""
 else UnhookWinEvent(_he) _he=0
