using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using Microsoft.Win32;
using System.Runtime.ExceptionServices;
using System.Windows.Forms;
using System.Drawing;
//using System.Linq;

using Catkeys;
using static Catkeys.NoClass;

partial class ThisIsNotAFormFile { }

partial class EForm
{
	partial class _Commands
	{
		#region menu File
		//Code generated by macro 'Generate Catkeys menu-toolbar command code'.

		public void File_NewScript()
		{
			//PrintFunc();
			_form.Model.NewItem(FileNode.NewItemTemplate.Script);
		}

		public void File_NewLibrary()
		{
			_form.Model.NewItem(FileNode.NewItemTemplate.Library);
		}

		public void File_NewFolder()
		{
			_form.Model.NewItem(FileNode.NewItemTemplate.Folder);
		}

		public void File_Import()
		{
			_form.Model.ImportFiles();
		}

		public void File_Disable()
		{
			DebugPrintFunc();

		}

		public void File_Rename()
		{
			_form.Model.RenameSelected();
		}

		public void File_Delete()
		{
			_form.Model.DeleteSelected();
		}

		public void File_Properties()
		{
			DebugPrintFunc();

		}

		public void File_Open()
		{
			_form.Model.OpenSelected(1);
		}

		public void File_OpenInNewWindow()
		{
			_form.Model.OpenSelected(2);
		}

		public void File_OpenInDefaultApp()
		{
			_form.Model.OpenSelected(3);
		}

		public void File_SelectInExplorer()
		{
			_form.Model.OpenSelected(4);
		}

		public void File_PreviousDocument()
		{
			DebugPrintFunc();

		}

		public void File_Close()
		{
			_form.Model.Close(1);
		}

		public void File_CloseAll()
		{
			_form.Model.Close(2);
		}

		public void File_CollapseFolders()
		{
			_form.Model.Close(3);
		}

		public void File_Cut()
		{
			_form.Model.CutCopySelected(true);
		}

		public void File_Copy()
		{
			_form.Model.CutCopySelected(false);
		}

		public void File_Paste()
		{
			_form.Model.Paste();
		}

		public void File_CopyRelativePath()
		{
			_form.Model.SelectedCopyPath(false);
		}

		public void File_CopyFullPath()
		{
			_form.Model.SelectedCopyPath(true);
		}

		public void File_PrintSetup()
		{

		}

		public void File_Print()
		{

		}

		public void File_OpenCollection()
		{
			_form.Panels.Files.LoadAnotherCollection();
		}

		public void File_NewCollection()
		{
			_form.Panels.Files.LoadNewCollection();
		}

		public void File_ExportCollection()
		{
			_form.Model.ExportSelected();
		}

		public void File_ImportCollection()
		{
			_form.Model.ImportCollection();
		}

		public void File_FindInCollections()
		{

		}

		public void File_CollectionProperties()
		{

		}

		public void File_SaveAllNow()
		{
			_form.Code.Save();
		}

		public void File_Exit()
		{
			_form.Close();
		}

		public void Edit_Undo()
		{

		}

		public void Edit_Redo()
		{

		}

		public void Edit_Cut()
		{

		}

		public void Edit_Copy()
		{

		}

		public void Edit_Paste()
		{

		}

		public void Edit_Find()
		{

		}

		public void Edit_Members()
		{

		}

		public void Edit_ContextHelp()
		{

		}

		public void Edit_GoToDefinition()
		{

		}

		public void Edit_PeekDefinition()
		{

		}

		public void Edit_FindReferences()
		{

		}

		public void Edit_Indent()
		{

		}

		public void Edit_Unindent()
		{

		}

		public void Edit_Comment()
		{

		}

		public void Edit_Uncomment()
		{

		}

		public void Edit_HideRegion()
		{

		}

		public void Edit_SelectAll()
		{

		}

		public void Edit_ImagesInCode()
		{

		}

		public void Edit_WrapLines()
		{

		}

		public void Edit_LineNumbers()
		{

		}

		public void Edit_IndentationGuides()
		{

		}

		public void Run_Run()
		{

		}

		public void Run_End()
		{

		}

		public void Run_Pause()
		{

		}

		public void Run_Compile()
		{

		}

		public void Run_AutoMinimize()
		{

		}

		public void Run_DisableTriggers()
		{

		}

		public void Run_MakeExe()
		{

		}

		public void Debug_RunToBreakpoint()
		{

		}

		public void Debug_RunToCursor()
		{

		}

		public void Debug_StepInto()
		{

		}

		public void Debug_StepOver()
		{

		}

		public void Debug_StepOut()
		{

		}

		public void Debug_ToggleBreakpoint()
		{

		}

		public void Debug_PersistentBreakpoint()
		{

		}

		public void Debug_ClearLocalBreakpoints()
		{

		}

		public void Debug_ClearAllBreakpoints()
		{

		}

		public void Debug_DebugOptions()
		{

		}

		public void Tools_Record()
		{

		}

		public void Tools_RecordMenu()
		{

		}

		public void Tools_RecordSingleAction()
		{

		}

		public void Tools_FilesAndTriggers()
		{

		}

		public void Tools_DialogEditor()
		{

		}

		public void Tools_ToolbarEditor()
		{

		}

		public void Tools_MenuEditor()
		{

		}

		public void Tools_ImagelistEditor()
		{

		}

		public void Tools_Resources()
		{

		}

		public void Tools_Icons()
		{

		}

		public void Tools_HelpEditor()
		{

		}

		public void Tools_RegularExpressions()
		{

		}

		public void Tools_ExploreWindows()
		{

		}

		public void Tools_RemapKeys()
		{

		}

		public void Tools_Components()
		{

		}

		public void Tools_Portable()
		{

		}

		public void Tools_Options()
		{

		}

		public void Tools_Output_Clear()
		{

		}

		public void Tools_Output_Copy()
		{

		}

		public void Tools_Output_FindSelectedText()
		{

		}

		public void Tools_Output_History()
		{

		}

		public void Tools_Output_LogWindowEvents()
		{

		}

		public void Tools_Output_LogAccEvents()
		{

		}

		public void Tools_Output_WrapLines()
		{

		}

		public void Tools_Output_WhiteSpace()
		{

		}

		public void Tools_Output_Topmost()
		{

		}

		public void Tools_Statusbar_Floating()
		{

		}

		public void Tools_Statusbar_MouseInfo()
		{

		}

		public void Tools_Statusbar_AutoHeight()
		{

		}

		public void Tools_Statusbar_SendToOutput()
		{

		}

		public void Help_QuickStart()
		{

		}

		public void Help_Reference()
		{

		}

		public void Help_ContextHelp()
		{

		}

		public void Help_Download()
		{

		}

		public void Help_Forum()
		{

		}

		public void Help_Email()
		{

		}

		public void Help_Donate()
		{

		}

		public void Help_About()
		{

		}

		#endregion handlers
	}
}
