PF
SystemParametersInfo(SPI_GETSCREENREADER 0 &_i 0)
PN
SystemParametersInfo(SPI_SETSCREENREADER 1 0 SPIF_SENDCHANGE)
 SystemParametersInfo(SPI_GETSCREENREADER 0 &_i 0)
 out _i
PN
SystemParametersInfo(SPI_SETSCREENREADER 0 0 SPIF_SENDCHANGE)
PN
PO
out _i
