 Creates pdf file from QM Help file or from some other .chm file.

 Before you run this macro, please review these values, and edit if need:
str chmFile="$qm$\QM2Help.chm" ;;QM Help file or some other .chm file
str pdfFile="$desktop$\QM Help.pdf" ;;the macro will create this pdf file
str pdfTitle="Quick Macros Help" ;;title of pdf file; don't use "
double zoom=1.3 ;;zoom pdf; 1.3 is good for QM Help
str wkhtmltopdfDir="$qm$\pdf\wkhtmltopdf" ;;folder of wkhtmltopdf.exe and related files

 _________________________________________________________________

 out
 RunConsole2 F"''{wkhtmltopdf_exe.expandpath}'' --extended-help"; ret ;;shows wkhtmltopdf help

OnScreenDisplay "Creating pdf, please wait" -1 0 0 0 0 0 8

str cl htmlDir.expandpath(F"$temp$\qm chm2pdf")

wkhtmltopdfDir.expandpath
 cl=F"''{wkhtmltopdfDir}\wkhtmltopdf.exe'' --quiet --title ''{pdfTitle}'' --zoom {zoom} --footer-center [page] --footer-font-size 9 --outline-depth 1 toc --xsl-style-sheet ''{wkhtmltopdfDir}\chm.xsl''" ;;use TOC generated by wkhtmltopdf
cl=F"''{wkhtmltopdfDir}\wkhtmltopdf.exe'' --quiet --title ''{pdfTitle}'' --zoom {zoom} --header-center [title] --header-font-size 9 --outline-depth 1" ;;use TOC generated by QMPDF_GetHtmlFiles (flag 1)

QMPDF_DecompileChm chmFile htmlDir
ARRAY(str) aFiles
QMPDF_GetHtmlFiles htmlDir cl aFiles 1
QMPDF_ProcessFiles htmlDir aFiles 1

cl+F" ''{pdfFile.expandpath}''"
 out cl; ret ;;<debug>

RunConsole2 cl
del- htmlDir

run pdfFile

 _____________________________________________________________

 wkhtmltopdf bug (fixed):
 Links jump to the middle of multipage topics. Only links from content; outline and wkhtmltopdf-generated TOC OK.
 http://code.google.com/p/wkhtmltopdf/issues/detail?id=411
 fix: 1. Add this in each html file, after <body>: <a name="top"></a>. 2. Append this to href of each local link: #top (unless already contains #).

 wkhtmltopdf bug (fixed):
 Some local links don't work. Added as extrnal links, some even with %5C instead of /.
 It seems that all such links are to COM subfolder, such as "../COM/file.html".
 fix: in a href replace COM to Com.

 wkhtmltopdf bug (fixed):
 no gif images. png OK.
 fix: convert to bmp.

 problem (fixed):
 No hidden sections. With Adobe Acrobat too.
 fix: in CSS file -> DIV.expand{}, remove this: display: none;

 wkhtmltopdf bug (fixed):
 Font in some pages is very small, unreadable. Eg in 'QM dll functions' topic.
 Because long lines in <pre> are not wrapped. Adobe Acrobat wraps these lines.
 fix: in CSS file -> PRE{}, add this: white-space: pre-wrap; word-wrap:break-word;

 note (fixed):
 By default, font too small when in normal zoom. Images too. Smaller than created by Adobe Acrobat.
 Use --zoom. Also can be used --minimum-font-size, --disable-smart-shrinking.

 note:
 At end outputs "Exit with code 2 due to http error: 404 Page not found", but creates pdf ok. Something in QM Grid topic.

 note:
 page breaking not perfect. Documented.

 wkhtmltopdf bug (fixed):
 does not generate TOC.
 fix: specify --xsl-style-sheet, generated by --dump-default-toc-xsl

 wkhtmltopdf bug or limitation (fixed):
 TOC contains items of all levels, even if --outline-depth 1. I need only first level.
 fix: edit xsl: to hide 2/3/4 level items, add this: ul ul li {display: none;}
 Need to edit anyway, eg change font size.

 wkhtmltopdf limitation:
 Does not have option to add custom outline, eg from xml. Automatically creates outline from headers; it is not what we need for chm.

 note:
 pdf file ~50% bigger than created by Adobe Acrobat.

 note:
 this macro tested only with qm2help.chm. Only on Windows 7.


 Why to use wkhtmltopdf if it is so buggy?
 1. Correctly renders html.
 2. Can run silently from macro (just single click: run macro and it creates pdf).
 3. Many options.
 4. Fast (compared to other html to pdf converters).
 5. This macro fixes the most important bugs and limitations.
 6. Free, small and easy to install.
 7. QM users can create pdf using this macro; it would be impossible with a commercial converter.
 8. I could not find a better free converter. All found commercial converters are too limited or buggy etc, except Adobe Acrobat which is too expensive if you need it only for this purpose.
