 out "<>text <c ''0xff0000''>color</c>"
 out "<>text <z ''0x8000''>bcolor</z>"
 out "<><Z ''0x8000''>bcolor</Z>"
 out "<><Z ''0xffff''></Z>"
 out "<>text <z ''0x8000''>bco[]lor</z>"
 out "<><Z ''0xffff''>text <c ''0xff00''>color</c> text</Z>"
 out "<><Z ''0xffff''>text <Z ''0xff00''>color</Z> text</Z>"
  out "<>text <c ''0xff0000''>co<b>lor</c>bbbb</b> text";; bad
 out "<><b>text</b>"
 out "<>ttt<c 0xff>co</c>"

out "<><c 0xff>co sssssssssssssss rrrrrrrrrrrrrrrr wwwwwwwwwwwwwwwww</c>"
out "<>text <c 0xff>co sssssssssssssss rrrrrrrrrrrrrrrr wwwwwwwwwwwwwwwww</c> text"
out "<>text <c 0xff>co sssssssssssssss <i>rrrrrrrrrrrrrrrr</i> wwwwwwwwwwwwwwwww</c> text"
out "<><c 0xff>A<c 0xff00>B</c>C</c>"
out "<><c 0xff>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<c 0xff00>BBBBBBBBBBBBB</c>CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC</c>"
out "<><c 0xff>A<c 0xff00>B</c>text"
out "<><c 0xff>A<c 0xff00>B</c></c>text"
out "<><c 0xff><c 0xff00>B</c>C</c>text"
 out "<><c 0xff>co sssssssssssssss <i>rrrrrrrrrrrrrrrr wwwwwwwwwwwwwwwww</c>mmmm</i>"
out "<><c 0xff>co sssssssssssssss <color ''0xff00''>green</color> wwwwwwwwwwwwwwwww</c>"
out "<><c 0xff>co sssssssssssssss <color ''0xff00''>gr<c 0xff0000>blue</c>een</color> wwwwwwwwwwwwwwwww</c>"
out "<><z 0xff>co sssssssssssssss <z ''0xff00''>gr<z 0xff0000>blue</z>een</z> wwwwwwwwwwwwwwwww</z>"
out "<><Z 0xff>co sssssssssssssss <z ''0xff00''>gr<z 0xff0000>blue</z>een</z> wwwwwwwwwwwwwwwww</Z>"

 out "<><c 0xff>co sssssssssssssss <notag ''dddddddddd dddddddd''>fff<color ''0xff00''>green</color>ffff</notag> wwwwwwwwwwwwwwwww</c>"
 out "<><Z 0xff>co sssssssssssssss <ii>gr<z 0xff0000>blue</z>een</ii> wwwwwwwwwwwwwwwww</Z>"
 out "<><z 0xff>co <ii>gr<z 0xff0000>blue</z>een ww</z>"
 out "<><z 0xff>co <x>gr<z 0xff0000>blue</z>een ww</z>"
