out
 out matchw("some STRING SOME string STRi" "some STRING SOME string STRi")
 out matchw("some STRING SOME string STRi" "some STRING SOME string STRi" 1)
 out matchw("stringing" "st*ing")
 out matchw("StringIng" "st*ing" 1)
 out matchw("a string strutis" "*str?tis")
 out matchw("a string StRuTis" "*str?tis" 1)
 out matchw("a Čėšų" "a Čėšų")
 out matchw("a Čėšų" "a čĖšų" 1)
 out matchw("a Čėšų" "a Č*ų")
 out matchw("a Čėšų" "a č*ų" 1)
 out matchw("a Čėšųth" "a Čėšų?h")
 out matchw("a Čėšųth" "a čĖšų?h" 1)
 out matchw("a Čėšų ąč ﯔﮥ qww" "a Č?šų ąč ?ﮥ qww")
 out matchw("a Čėšų ąč ﯔﮥ qww" "a č?šų ąč ?ﮥ qww" 1)
 out matchw("a Čėšų ąč ﯔﮥﯔﮥ qww" "a Č??ų ąč ???ﮥ qww")
 out matchw("a Čėšų ąč ﯔﮥﯔﮥ qww" "a č??ų ąč ???ﮥ qww" 1)
 out matchw("some STRING SOME string STRi" "* SOME string STRi")
 out matchw("some STRING SOME string STRi" "* SOME string STRi" 1)
 out matchw("some STRING SOME string STRi" "some STRING SOME*")
 out matchw("some STRING SOME string STRi" "some STRING SOME*" 1)
 out matchw("some STRING SOME string STRi" "* SOME *")
 out matchw("some STRING SOME string STRi" "* SOME *" 1)
 out matchw("some STRING SOME string STRi" "?* SOME ?*")
 out matchw("some STRING SOME string STRi" "?* SOME ?*" 1)
 out matchw("some STRING SOME string STRi" "?ome STRING SOME string STR?")
 out matchw("some STRING SOME string STRi" "?ome STRING SOME string STR?" 1)
 out matchw("some STRING SOME string STRi" "???? STRING SOME string STR?")
 out matchw("some STRING SOME string STRi" "???? STRING SOME string STR?" 1)
 out matchw("Čėšų ąč ﯔﮥﯔﮥ" "???ų ąč ????")
 out matchw("Čėšų ąč ﯔﮥﯔﮥ" "???ų ąč ????" 1)
 out matchw("some STRING " "some*STRING?")
 out matchw("some STRING " "some*STRING?" 1)
 out matchw("some*STRING?" "some*STRING?")
 out matchw("some*STRING?" "some*STRING?" 1)
 out matchw("some STRING " "some**STRING*?")
 out matchw("some STRING " "some**STRING*?" 1)
 out matchw("some*STRING?" "some**STRING*?")
 out matchw("some*STRING?" "some**STRING*?" 1)
 out matchw("some STRING" "*some STRING*")
 out matchw("some STRING" "*some STRING*" 1)
 out matchw("some STRING" "*")
 out matchw("some STRING" "*" 1)
 out matchw("some STRING" "?*")
 out matchw("some STRING" "?*" 1)
 out matchw("" "*")
 out matchw("" "*" 1)
 out matchw("" "?*")
 out matchw("" "?*" 1)
 out matchw("s" "?*")
 out matchw("s" "?*" 1)
