str ind="$desktop$\ąčﯔﮥ q"
 str ind="$desktop$"
if(!OpenSaveDialog(0 _s "Č files[]*.txt[]Ū files[]*.cpp[]" "" ind "šį")) out "failed"; ret
out _s

#if 0
CDERR_DIALOGFAILURE
CDERR_FINDRESFAILURE
CDERR_NOHINSTANCE
CDERR_INITIALIZATION
CDERR_NOHOOK
CDERR_LOCKRESFAILURE
CDERR_NOTEMPLATE
CDERR_LOADRESFAILURE
CDERR_STRUCTSIZE
CDERR_LOADSTRFAILURE
FNERR_BUFFERTOOSMALL
CDERR_MEMALLOCFAILURE
FNERR_INVALIDFILENAME
CDERR_MEMLOCKFAILURE
FNERR_SUBCLASSFAILURE
