str ind="$desktop$\ąčﯔﮥ q"
 str ind="$desktop$"
ARRAY(str) a
if(!OpenSaveDianog(0 0 "All files[]*.*[]Č files[]*.txt[]Ū files[]*.cpp" "" ind "šį" 0 a)) out "failed"; ret
int i
for i 0 a.len
	out a[i]

#if 0
CDERR_DIALOGFAILURE
CDERR_FINDRESFAILURE
CDERR_NOHINSTANCE
CDERR_INITIALIZATION
CDERR_NOHOOK
CDERR_LOCKRESFAILURE
CDERR_NOTEMPLATE
CDERR_LOADRESFAILURE
CDERR_STRUCTSIZE
CDERR_LOADSTRFAILURE
FNERR_BUFFERTOOSMALL
CDERR_MEMALLOCFAILURE
FNERR_INVALIDFILENAME
CDERR_MEMLOCKFAILURE
FNERR_SUBCLASSFAILURE
