CompactFunction :mac "CompactFunction"
CompactFunction CCall :mac "CompactFunction" 0 1
 VC grid 4 :mac "VC grid 4"
Implement interface :mac "II_Main3"
VC grid 4 :mac "VC grid 4"
Toggle Navigation Bar :mac "MSDEV_NavBar"
Toggle Intellisense :mac "MSDEV_Intellisense"
Add link to Help :mac "TipsHelpLink"
VS comments move before function[9]Alt+C :mac "VS comments move before function"
CompactFunction and create API hook :mac "CompactFunction and create API hook"
 VS #define to enum :mac "VS #define to enum"
 C++ #define to C# enum :mac "C++ #define to C# enum"
C++ #define to C# const :mac "C++ #define to C# const"
VS collapse Solution :mac "VS collapse Solution"
