interface# IMarkupContainer :IUnknown
	OwningDoc(IHTMLDocument2*ppDoc)
	{3050f5f9-98b5-11cf-bb82-00aa00bdce0b}

interface# IMarkupPointer :IUnknown
	OwningDoc(IHTMLDocument2*ppDoc)
	Gravity(*pGravity)
	SetGravity(Gravity)
	Cling(*pfCling)
	SetCling(fCLing)
	Unposition()
	IsPositioned(*pfPositioned)
	GetContainer(IMarkupContainer'ppContainer)
	MoveAdjacentToElement(IHTMLElement'pElement eAdj)
	MoveToPointer(IMarkupPointer'pPointer)
	MoveToContainer(IMarkupContainer'pContainer fAtStart)
	Left(fMove *pContext IHTMLElement*ppElement *pcch @*pchText)
	Right(fMove *pContext IHTMLElement*ppElement *pcch @*pchText)
	CurrentScope(IHTMLElement*ppElemCurrent)
	IsLeftOf(IMarkupPointer'pPointerThat *pfResult)
	IsLeftOfOrEqualTo(IMarkupPointer'pPointerThat *pfResult)
	IsRightOf(IMarkupPointer'pPointerThat *pfResult)
	IsRightOfOrEqualTo(IMarkupPointer'pPointerThat *pfResult)
	IsEqualTo(IMarkupPointer'pPointerThat *pfAreEqual)
	MoveUnit(muAction)
	FindTextA(@*pchFindText dwFlags IMarkupPointer'pIEndMatch IMarkupPointer'pIEndSearch)
	{3050f49f-98b5-11cf-bb82-00aa00bdce0b}

interface# IMarkupServices :IUnknown
	CreateMarkupPointer(IMarkupPointer*ppPointer)
	CreateMarkupContainer(IMarkupContainer*ppMarkupContainer)
	CreateElement(tagID @*pchAttributes IHTMLElement*ppElement)
	CloneElement(IHTMLElement'pElemCloneThis IHTMLElement*ppElementTheClone)
	InsertElement(IHTMLElement'pElementInsert IMarkupPointer'pPointerStart IMarkupPointer'pPointerFinish)
	RemoveElement(IHTMLElement'pElementRemove)
	Remove(IMarkupPointer'pPointerStart IMarkupPointer'pPointerFinish)
	Copy(IMarkupPointer'pPointerSourceStart IMarkupPointer'pPointerSourceFinish IMarkupPointer'pPointerTarget)
	Move(IMarkupPointer'pPointerSourceStart IMarkupPointer'pPointerSourceFinish IMarkupPointer'pPointerTarget)
	InsertText(@*pchText cch IMarkupPointer'pPointerTarget)
	ParseString(@*pchHTML dwFlags IMarkupContainer*ppContainerResult IMarkupPointer'ppPointerStart IMarkupPointer'ppPointerFinish)
	ParseGlobal(hglobalHTML dwFlags IMarkupContainer*ppContainerResult IMarkupPointer'pPointerStart IMarkupPointer'pPointerFinish)
	IsScopedElement(IHTMLElement'pElement *pfScoped)
	GetElementTagId(IHTMLElement'pElement *ptagId)
	GetTagIDForName(BSTR'bstrName *ptagId)
	GetNameForTagID(tagId BSTR*pbstrName)
	MovePointersToRange(IHTMLTxtRange'pIRange IMarkupPointer'pPointerStart IMarkupPointer'pPointerFinish)
	MoveRangeToPointers(IMarkupPointer'pPointerStart IMarkupPointer'pPointerFinish IHTMLTxtRange'pIRange)
	BeginUndoUnit(@*pchTitle)
	EndUndoUnit()
	{3050f4a0-98b5-11cf-bb82-00aa00bdce0b}
