
m_syn._create
_s=
 macro,qm-item
 function,procedure,api,method
 get,return,retrieve,receive,know,determine
 run,execute,start,launch,begin,activate,call
 text,string
 need,require,necessary
 trigger,activate,cause
 make,made,create,cause
 time,date,period
 try,test,evaluate
 find,found,search
 click,press
 know,get,return,retrieve,determine
 create,make,made,implement
 program,applic,exe,process
 change,replace,edit,modify,convert,switch,substitute
 name,identify
 set,define,change,make,
 control,child,window,object
 error,fail,exception,mistake,incorrect,wrong,bad
 line,statement
 folder,directory
 wait,delay,pause
 open,run,launch,load
 mouse,cursor
 string,text,str
 type,write,press,send,class
 start,run,launch,begin,initialize,activate,play,turn,call
 number,count,digit
 edit,change,modify
 add,append
 box,dialog,control,list,combo
 test,evaluate,try,compare
 user,account
 object,control
 show,display,output
 command,function,statement,keyword
 item,element
 list,listbox,enumerate,enum
 message,event
 another,other,different
 after,follow,behind,later
 icon,image,picture
 computer,pc
 int,integer
 id,identifier,control
 search,find,look
 differ,other,another
 option,setting,flag
 end,return,exit,close,stop,break,termin,destroy,cancel,kill,turn,hide
 save,keep,persist,store,write,apply
 read,get,take,receive,retrieve
 image,picture,icon,bitmap
 put,assign,set,place
 copy,duplicate
 activ,focus,foreground,trigger,run,launch,start
 each,every,all,enumerate,enum
 screen,display,monitor
 color,colour
 colour,color
 keyboard,key,hotkey
 data,file,info,inform
 send,transfer,type,paste
 word,string
 press,click,down
 web,internet,webpage,browser
 return,get,exit,cancel
 delete,remove,erase,clear,drop,empty
 close,exit,destroy,cancel,hide
 stop,break,end,pause,exit,return,cancel,terminate,kill
 down,shutdown
 many,multiple,several
 replace,change,substitute
 current,this
 format,type
 download,get,retrieve,transfer
 process,program,applic
 action,command,function,statement
 document,file
 must,necessary,require,should
 editor,code,text
 output,display,show
 display,show,screen,monitor,output
 write,save,store,type,send
 record,capture,type,row
 applic,app,program,exe,process,software
 install,setup
 script,macro,qm-item
 handle,manage,manipulate,object
 property,attribute,info,data
 let,allow
 field,box,control,object
 follow,after,next
 enter,type,paste,set,ok,line,return
 multiple,many,several
 remove,delete,erase,drop
 place,add,put
 internet,web,ie
 over,above
 take,get,read
 explor,ie
 update,change,upgrade,replace,modify
 exist,found,miss,empty
 link,shortcut
 keep,continue,save
 info,inform,property,attribute,data
 bar,toolbar
 size,dimens,length
 contain,include,has,have,find,found
 gener,create,make
 execute,run,start,launch,begin,activate,call
 path,file,filename
 net,internet,network,web
 convert,change,make,modify,replace
 flag,option
 through,using
 software,program,app,applic
 off,shutdown
 date,time
 inform,info,property,attribute,data
 child,control
 default,initial
 load,open,get
 app,applic,program,exe,process,software
 fail,error,exception
 wrong,incorrect,bad
 every,all,each
 above,over
 log,record
 encrypt,encode
 ie,internet
 several,multiple
 until,while
 url,address
 little,small
 begin,start
 correct,adjust,change,modify
 repeat,loop,each
 drop,remove,delete
 below,under
 task,thread,macro
 loop,repeat,rep,each
 store,save,receive,get,set,assign
 statement,code,command,function,keyword
 assign,set,get,store,receive
 event,message
 everyth,all
 modify,change,edit
 play,run,execute,sound
 point,pixel,dot,coordinate
 compile,make,create
 account,user
 declare,define
 capture,record
 monitor,display,screen
 shortcut,hotkey,run
 space,spacebar,blank
 launch,run,execute,start,begin,activate,call
 method,way,member,function
 way,method
 pc,computer
 index,indic,position,offset
 indic,index,position,offset
 position,index,indic,offset
 match,equal,same,find,compare
 order,sort,position
 sort,order
 eg,example,instance
 content,data
 appear,found,exist
 resize,size
 argument,parameter
 normal,usual
 define,declare
 website,web,internet,url
 tool,toolbar,dialog
 visible,invisible,hidden
 automat,auto,implicit
 refer,point,link,help
 view,show,see,look
 address,pointer,url
 area,field
 custom,user
 site,website,url,address
 restart,reboot
 locat,find,position
 title,caption,label,name
 extract,find,get
 form,dialog,window
 miss,found,exist,empty
 interface,class,ui
 receive,retrieve,get,read
 share,distribute,global
 combo,combobox
 directory,folder
 release,up,free
 turn,shutdown
 pop,popup
 hide,close
 cursor,mouse,caret
 speed,wait,delay,fast,faster,slow,slower
 separate,different
 complete,finish,whole,full,entire
 step,statement,line,command
 usual,normal
 require,must,need,necessary,optional
 empty,miss,found,exist
 sample,example
 float,double
 fast,speed
 faster,speed
 switch,sel
 old,previous
 enable,disable
 disable,enable
 small,little
 picture,image,icon,bitmap
 comment,disable
 avail,exist
 full,whole
 api,function
 tray,notif
 combine,join,from,format,compose
 filename,path
 septup,install
 coordinate,position
 mail,email
 calcul,comput,get
 block,prevent,statement,allow,deny
 previous,old,preceding
 direct,immediate
 zip,compress
 export,save,convert,format
 clear,empty,delete,erase,clean
 via,through,using
 mode,style
 oper,action
 detect,discover,find
 free,release,empty
 parameter,argument
 remember,save,memory,variable
 hotkey,key,keyboard
 hilite,highlight
 middle,center,between
 regex,regular
 regexp,regular
 count,number,length,size
 gui,ui,dialog,editor
 instance,example,case
 entry,item
 enumerate,foreach,array,list,enum
 if,whether
 whether,if
 sheet,worksheet
 webpage,web,internet,url,website
 pointer,cursor,address,reference
 delay,wait,pause
 focus,activate,select
 exit,return,end,break
 letter,character
 print,output
 label,text,description
 implement,create
 ff,firefox
 build,create,make,format
 perform,speed
 grab,capture
 draw,paint
 navigate,open
 bitmap,picture,image
 choose,select
 total,whole,entire,full,complete
 finish,end,complete,exit
 crash,hang,hung,stop,exception,error,fail
 true,real,actual
 real,actual,true
 shutdown,shut,turn
 definit,declarat
 declarat,definit
 response,reply,result,answer
 pause,wait,delay
 big,large
 amount,count,number
 shell,explorer
 standard,usual,common
 combobox,combo
 hold,press
 restore,backup
 leave,exit,return,break
 integer,int
 popul,fill,store
 checkbox,check
 arrow,cursor,pointer
 admin,administrator
 suppose,assume
 reset,clear
 wheel,middle,scroll
 eat,filter,block
 bad,incorrect,wrong
 audio,sound
 multi,multiple
 login,logon
 length,size,number,count
 cancel,stop,end,close
 push,press
 upgrade,update,install
 username,user
 os,windows
 blank,space,empty,clean
 entire,full,whole
 center,middle,between
 whatever,any
 extra,addit
 max,maxim
 shut,shutdown,turn
 older,old,previous
 webbrowser,browser
 necessary,require
 

 line 816 in "synonyms for...", last added "necessary"

 administrator,admin
 erase,delete,remove,clear
 element,item
_s.stem(1)
_s.findreplace(" ")
m_syn.AddList(_s ",")
