 /CtoQM
function $preproc_def !noDefaults

 Preprocessor definitions.

IStringMap mc=CreateStringMap(4)

lpstr s=
 WINVER 0x0601
 _WIN32_WINNT 0x0601
 NTDDI_VERSION 0x06010000
 _WIN32_IE 0x0800
 _MFC_VER 0x0710
 WIN32
 _WIN32 1
 _WINDOWS
 __cplusplus 199711
 _MSC_VER 1310
 _MSC_EXTENSIONS 1
 _CRTIMP
 _MT 1
 NDEBUG
 STRICT 1
 _INTEGRAL_MAX_BITS 64
 __cdecl
 _M_IX86 600
 INTERNET_FLAG_BGUPDATE 0x00000008
if(!noDefaults) mc.AddList(s)
if(len(preproc_def)) mc.AddList(preproc_def)
mc.GetList(_s)
if(_s.len) m_mc.AddList(_s)

 INTERNET_FLAG_BGUPDATE is not defined (found in Internet)

 _________________________________________

 These are added here because could not be calculated.

s=
 REPARSE_GUID_DATA_BUFFER_HEADER_SIZE 24
 NOTIFYICONDATAA_V1_SIZE 88
 NOTIFYICONDATAW_V1_SIZE 152
 PROPSHEETPAGEA_V1_SIZE 40
 PROPSHEETPAGEW_V1_SIZE 40
 PROPSHEETPAGEA_V2_SIZE 48
 PROPSHEETPAGEW_V2_SIZE 48
 PROPSHEETHEADERA_V1_SIZE 40
 PROPSHEETHEADERW_V1_SIZE 40
 OPENFILENAME_SIZE_VERSION_400A 76
 OPENFILENAME_SIZE_VERSION_400W 76
 SHELLSTATE_SIZE_WIN95 12
 SHELLSTATE_SIZE_NT4 20
 SHELLSTATE_SIZE_IE4 24
 IMAGELISTDRAWPARAMS_V3_SIZE 56
 HDITEMA_V1_SIZE 28
 HDITEMW_V1_SIZE 28
 REBARBANDINFOA_V3_SIZE 56
 REBARBANDINFOW_V3_SIZE 56
 TTTOOLINFOA_V1_SIZE 40
 TTTOOLINFOW_V1_SIZE 40
 TTTOOLINFOA_V2_SIZE 44
 TTTOOLINFOW_V2_SIZE 44
 TTTOOLINFOA_V3_SIZE 48
 TTTOOLINFOW_V3_SIZE 48
 NMTTDISPINFOA_V1_SIZE 104
 NMTTDISPINFOW_V1_SIZE 184
 LVITEMA_V1_SIZE 36
 LVITEMW_V1_SIZE 36
 LVHITTESTINFO_V1_SIZE 16
 LVCOLUMNA_V1_SIZE 24
 LVCOLUMNW_V1_SIZE 24
 TVINSERTSTRUCTA_V1_SIZE 48
 TVINSERTSTRUCTW_V1_SIZE 48
 NMTVCUSTOMDRAW_V3_SIZE 56
if(!noDefaults) m_mc.AddList(s "")

 _________________________________________

if(!noDefaults and !m_pch)
	m_mf.Add("IsEqualGUID" "dll C_macro IsEqualGUID GUID*guid1 GUID*guid2[] ;;!memcmp(guid1,guid2,sizeof(GUID))")
	if(!m_compact)
		s=
 MSOAPI_ (a) a
		m_mcf.AddList(s "")
