 CONSTANTS
def CURLOPT_VERBOSE 41
def CURLOPT_HEADER 42
def CURLOPT_NOPROGRESS 43
def CURLOPT_NOSIGNAL 99
def CURLOPT_WRITEFUNCTION 20011
def CURLOPT_FILE 10001
def CURLOPT_WRITEDATA 10001
def CURLOPT_READFUNCTION 20012
def CURLOPT_READDATA 10009
def CURLOPT_PROGRESSFUNCTION 20056
def CURLOPT_PROGRESSDATA 10057
def CURLOPT_PASSWDFUNCTION 20066
def CURLOPT_PASSWDDATA 10067
def CURLOPT_HEADERFUNCTION 20079
def CURLOPT_WRITEHEADER 10029
def CURLOPT_DEBUGFUNCTION 20094
def CURLOPT_ERRORBUFFER 10010
def CURLOPT_STDERR 10037
def CURLOPT_FAILONERROR 45
def CURLOPT_URL 10002
def CURLOPT_PROXY 10004
def CURLOPT_PROXYPORT 59
def CURLOPT_PROXYTYPE 101
def CURLOPT_HTTPPROXYTUNNEL 61
def CURLOPT_INTERFACE 10062
def CURLOPT_DNS_CACHE_TIMEOUT 92
def CURLOPT_DNS_USE_GLOBAL_CACHE 91
def CURLOPT_BUFFERSIZE 98
def CURLOPT_NETRC 51
def CURLOPT_USERPWD 10005
def CURLOPT_PROXYUSERPWD 10006
def CURLOPT_HTTPAUTH 107
def CURLOPT_ENCODING 10102
def CURLOPT_FOLLOWLOCATION 52
def CURLOPT_UNRESTRICTED_AUTH 105
def CURLOPT_MAXREDIRS 68
def CURLOPT_PUT 54
def CURLOPT_POST 47
def CURLOPT_POSTFIELDS 10015
def CURLOPT_POSTFIELDSIZE 60
def CURLOPT_HTTPPOST 10024
def CURLOPT_REFERER 10016
def CURLOPT_USERAGENT 10018
def CURLOPT_HTTPHEADER 10023
def CURLOPT_HTTP200ALIASES 10104
def CURLOPT_COOKIE 10022
def CURLOPT_COOKIEFILE 10031
def CURLOPT_COOKIEJAR 10082
def CURLOPT_TIMECONDITION 33
def CURLOPT_TIMEVALUE 34
def CURLOPT_HTTPGET 80
def CURLOPT_HTTP_VERSION 84
def CURLOPT_FTPPORT 10017
def CURLOPT_QUOTE 10028
def CURLOPT_POSTQUOTE 10039
def CURLOPT_PREQUOTE 10093
def CURLOPT_FTPLISTONLY 48
def CURLOPT_FTPAPPEND 50
def CURLOPT_FTP_USE_EPRT 106
def CURLOPT_TRANSFERTEXT 53
def CURLOPT_CRLF 27
def CURLOPT_RANGE 10007
def CURLOPT_RESUME_FROM 21
def CURLOPT_CUSTOMREQUEST 10036
def CURLOPT_FILETIME 10069
def CURLOPT_NOBODY 44
def CURLOPT_INFILESIZE 14
def CURLOPT_UPLOAD 46
def CURLOPT_TIMEOUT 13
def CURLOPT_LOW_SPEED_LIMIT 19
def CURLOPT_LOW_SPEED_TIME 20
def CURLOPT_MAXCONNECTS 71
def CURLOPT_CLOSEPOLICY 72
def CURLOPT_FRESH_CONNECT 74
def CURLOPT_FORBID_REUSE 75
def CURLOPT_CONNECTTIMEOUT 78
def CURLOPT_SSLCERT 10025
def CURLOPT_SSLCERTTYPE 10086
def CURLOPT_SSLCERTPASSWD 10026
def CURLOPT_SSLKEY 10087
def CURLOPT_SSLKEYTYPE 10088
def CURLOPT_SSLKEYPASSWD 10026
def CURLOPT_SSLVERSION 32
def CURLOPT_SSL_VERIFYPEER 64
def CURLOPT_CAINFO 10065
def CURLOPT_RANDOM_FILE 10076
def CURLOPT_EGDSOCKET 10077
def CURLOPT_SSL_VERIFYHOST 81
def CURLOPT_SSL_CIPHER_LIST 10083
def CURLOPT_KRB4LEVEL 10063
def CURL_NETRC_OPTIONAL 1
def CURL_NETRC_IGNORED 0
def CURL_NETRC_REQUIRED 2
def CURLAUTH_BASIC 1
def CURLAUTH_DIGEST 2
def CURLAUTH_GSSNEGOTIATE 4
def CURLAUTH_NTLM 8
def CURLAUTH_ANY -1
def CURLAUTH_ANYSAFE -2
def CURL_HTTP_VERSION_NONE 0
def CURL_HTTP_VERSION_1_0 1
def CURL_HTTP_VERSION_1_1 2
def HTTPPOST_FILENAME (1<<0)
def HTTPPOST_READFILE (1<<1)
def HTTPPOST_PTRNAME (1<<2)
def HTTPPOST_PTRCONTENTS (1<<3)
def HTTPPOST_BUFFER (1<<4)
def HTTPPOST_PTRBUFFER (1<<5)
def CURL_MAX_WRITE_SIZE 16384
def CURLE_OPERATION_TIMEDOUT CURLE_OPERATION_TIMEOUTED
def CURLE_HTTP_NOT_FOUND CURLE_HTTP_RETURNED_ERROR
def CURLAUTH_NONE 0
def CURLE_ALREADY_COMPLETE 99999
def CURLE_FTP_PARTIAL_FILE CURLE_PARTIAL_FILE
def CURLE_FTP_BAD_DOWNLOAD_RESUME CURLE_BAD_DOWNLOAD_RESUME
def CURL_ERROR_SIZE 256
def CURLOPTTYPE_LONG 0
def CURLOPTTYPE_OBJECTPOINT 10000
def CURLOPTTYPE_FUNCTIONPOINT 20000
def CURL_ISOCPP 1
def LONG CURLOPTTYPE_LONG
def OBJECTPOINT CURLOPTTYPE_OBJECTPOINT
def FUNCTIONPOINT CURLOPTTYPE_FUNCTIONPOINT
def CURLOPT_HEADERDATA CURLOPT_WRITEHEADER
def TIMECOND_IFMODSINCE CURL_TIMECOND_IFMODSINCE
def TIMECOND_IFUNMODSINCE CURL_TIMECOND_IFUNMODSINCE
def TIMECOND_LASTMOD CURL_TIMECOND_LASTMOD
def CURLINFO_STRING 0x100000
def CURLINFO_LONG 0x200000
def CURLINFO_DOUBLE 0x300000
def CURLINFO_MASK 0x0fffff
def CURLINFO_TYPEMASK 0xf00000
def CURL_GLOBAL_SSL (1<<0)
def CURL_GLOBAL_WIN32 (1<<1)
def CURL_GLOBAL_ALL (CURL_GLOBAL_SSL|CURL_GLOBAL_WIN32)
def CURL_GLOBAL_NOTHING 0
def CURL_GLOBAL_DEFAULT CURL_GLOBAL_ALL
def CURLFORM_COPYNAME 1
def CURLFORM_NAMELENGTH 3
def CURLFORM_PTRNAME 2
def CURLFORM_NAMELENGTH 3
def CURLFORM_COPYCONTENTS 4
def CURLFORM_CONTENTSLENGTH 6
def CURLFORM_PTRCONTENTS 5
def CURLFORM_FILECONTENT 7
def CURLFORM_FILE 10
def CURLFORM_CONTENTTYPE 14
def CURLFORM_FILENAME 16
def CURLFORM_BUFFERPTR 12
def CURLFORM_BUFFERLENGTH 13
def CURLFORM_ARRAY 8
def CURLFORM_END 17
def CURLFORM_CONTENTHEADER 15
 TYPES
type CURL byte*b ;;handle
type curl_slist $data curl_slist*next
type HttpPost HttpPost*next $name namelength $contents contentslength $buffer bufferlength $contenttype curl_slist*contentheader HttpPost*more flags $showfilenamedef
type curl_forms  option $value
 FUNCTIONS
dll "C:\Documents and Settings\a\Desktop\FromDesktop\curl-7.10.6\lib\Release\libcurl.dll"
	#curl_global_init flags
	curl_global_cleanup
	CURL'curl_easy_init
	#curl_easy_setopt CURL'curl option parameter
	#curl_easy_perform CURL'curl
	curl_easy_cleanup CURL'curl
	#curl_easy_getinfo CURL'curl info parameter
	CURL'curl_easy_duphandle CURL'curl
	$curl_escape $url length
	$curl_unescape $string length
	curl_free !*ptr
	#curl_formadd ;;#curl_formadd HttpPost**httppost HttpPost**last_post ...
	curl_formfree HttpPost*form
	curl_slist*curl_slist_append curl_slist*list $data
	curl_slist_free_all curl_slist*list
