 out
str cmd=
 File_NewScript
 File_NewLibrary
 File_NewFolder
 File_Import
 File_Disable
 File_Rename
 File_Delete
 File_Properties
 File_Open
 File_OpenInNewWindow
 File_SelectInExplorer
 File_PreviousDocument
 File_Close
 File_CloseAll
 File_CollapseFolders
 File_CopyName
 File_CopyPath
 File_SelectMultiple
 File_Cut
 File_Copy
 File_Paste
 File_Clone
 File_PrintSetup
 File_Print
 File_OpenCollection
 File_ImportCollection
 File_ExportCollection
 File_FindInCollections
 File_CollectionProperties
 File_SaveAllNow
 File_CloseWindow
 File_ExitProgram
 Edit_Undo
 Edit_Redo
 Edit_Cut
 Edit_Copy
 Edit_Paste
 Edit_Find
 Edit_Members
 Edit_ContextHelp
 Edit_GoToDefinition
 Edit_PeekDefinition
 Edit_FindReferences
 Edit_Indent
 Edit_Unindent
 Edit_Comment
 Edit_Uncomment
 Edit_HideRegion
 Edit_SelectAll
 Edit_ImagesInCode
 Edit_WrapLines
 Edit_LineNumbers
 Edit_IndentationGuides
 Run_Run
 Run_End
 Run_Pause
 Run_Compile
 Run_AutoMinimize
 Run_DisableTriggers
 Run_MakeExe
 Debug_RunToBreakpoint
 Debug_RunToCursor
 Debug_StepInto
 Debug_StepOver
 Debug_StepOut
 Debug_ToggleBreakpoint
 Debug_PersistentBreakpoint
 Debug_ClearLocalBreakpoints
 Debug_ClearAllBreakpoints
 Debug_DebugOptions
 Tools_Record
 Tools_RecordMenu
 Tools_RecordSingleAction
 Tools_FilesAndTriggers
 Tools_DialogEditor
 Tools_ToolbarEditor
 Tools_MenuEditor
 Tools_ImagelistEditor
 Tools_Resources
 Tools_Icons
 Tools_HelpEditor
 Tools_RegularExpressions
 Tools_ExploreWindows
 Tools_RemapKeys
 Tools_Components
 Tools_Portable
 Tools_Options
 Tools_Output_Clear
 Tools_Output_Copy
 Tools_Output_FindSelectedText
 Tools_Output_History
 Tools_Output_LogWindowEvents
 Tools_Output_LogAccEvents
 Tools_Output_WrapLines
 Tools_Output_WhiteSpace
 Tools_Output_Topmost
 Tools_Statusbar_Floating
 Tools_Statusbar_MouseInfo
 Tools_Statusbar_AutoHeight
 Tools_Statusbar_SendToOutput
 Help_QuickStart
 Help_Reference
 Help_ContextHelp
 Help_Download
 Help_Forum
 Help_Email
 Help_Donate
 Help_About

str sAdd sFunc s
sAdd+"#region add to _commands[]//Code generated by macro 'Generate Catkeys menu-toolbar command code'.[][]"
sFunc+"#region handlers[]//Code generated by macro 'Generate Catkeys menu-toolbar command code'.[][]"
foreach s cmd
	sAdd+F"_commands.Add(nameof({s}), {s});[]"
	sFunc+F"public void {s}()[]{{[][9][]}[][]"
sAdd+"[]#endregion add[][]"
sFunc+"#endregion handlers[]"

 out sAdd
sAdd.setclip
mes "Paste _commands.Add, then close this box and paste functions."
 out sFunc
sFunc.setclip
