lpstr files=
 C:\Windows\system32\12520437.cpx
 C:\Windows\system32\12520850.cpx
 C:\Windows\system32\7B296FB0-376B-497e-B012-9C450E1B7327-2P-0.C7483456-A289-439d-8115-601632D005A0
 C:\Windows\system32\7B296FB0-376B-497e-B012-9C450E1B7327-2P-1.C7483456-A289-439d-8115-601632D005A0
 C:\Windows\system32\8point1.wav
 C:\Windows\system32\a3d.dll
 C:\Windows\system32\aaclient.dll
 C:\Windows\system32\accessibilitycpl.dll
 C:\Windows\system32\ACCTRES.dll
 C:\Windows\system32\acledit.dll
 C:\Windows\system32\aclui.dll
 C:\Windows\system32\acppage.dll
 C:\Windows\system32\acprgwiz.dll
 C:\Windows\system32\ActionQueue.dll
 C:\Windows\system32\ActiveContentWizard.dll
 C:\Windows\system32\activeds.dll
 C:\Windows\system32\activeds.tlb
 C:\Windows\system32\actskin4.ocx
 C:\Windows\system32\actxprxy.dll
 C:\Windows\system32\ACW.exe
 C:\Windows\system32\acwizard.ico
 C:\Windows\system32\AdapterTroubleshooter.exe
 C:\Windows\system32\admparse.dll
 C:\Windows\system32\ADODC.SRG
 C:\Windows\system32\adsldp.dll
 C:\Windows\system32\adsldpc.dll
 C:\Windows\system32\adsmsext.dll
 C:\Windows\system32\adsnt.dll
 C:\Windows\system32\adtschema.dll
 C:\Windows\system32\advapi32.dll
 C:\Windows\system32\advpack.dll
 C:\Windows\system32\aecache.dll
 C:\Windows\system32\aelupsvc.dll
 C:\Windows\system32\alg.exe
 C:\Windows\system32\AltTab.dll
 C:\Windows\system32\amcompat.tlb
 C:\Windows\system32\amstream.dll
 C:\Windows\system32\amxread.dll
 C:\Windows\system32\anim.dll
 C:\Windows\system32\ANSI.SYS
 C:\Windows\system32\apds.dll
 C:\Windows\system32\apilogen.dll
 C:\Windows\system32\apircl.dll
 C:\Windows\system32\append.exe
 C:\Windows\system32\apphelp.dll
 C:\Windows\system32\Apphlpdm.dll
 C:\Windows\system32\appinfo.dll
 C:\Windows\system32\appmgmts.dll
 C:\Windows\system32\appmgr.dll
 C:\Windows\system32\appverif.chm
 C:\Windows\system32\appverif.exe
 C:\Windows\system32\appverif.ico
 C:\Windows\system32\appverif.pdb
 C:\Windows\system32\appwiz.cpl
 C:\Windows\system32\apss.dll
 C:\Windows\system32\ARP.EXE
 C:\Windows\system32\asferror.dll
 C:\Windows\system32\aswBoot.exe
 C:\Windows\system32\asycfilt.dll
 C:\Windows\system32\at.exe
 C:\Windows\system32\AtBroker.exe
 C:\Windows\system32\atl.dll
 C:\Windows\system32\atl71.dll
 C:\Windows\system32\atl71.pdb
 C:\Windows\system32\atmfd.dll
 C:\Windows\system32\atmlib.dll
 C:\Windows\system32\attrib.exe
 C:\Windows\system32\audiodev.dll
 C:\Windows\system32\audiodg.exe
 C:\Windows\system32\AudioEng.dll
 C:\Windows\system32\AUDIOKSE.dll
 C:\Windows\system32\AudioPlayerActiveX.dll
 C:\Windows\system32\AudioSes.dll
 C:\Windows\system32\audiosrv.dll
 C:\Windows\system32\auditpol.exe
 C:\Windows\system32\Aurora.scr
 C:\Windows\system32\authfwcfg.dll
 C:\Windows\system32\AuthFWGP.dll
 C:\Windows\system32\AuthFWSnapin.dll
 C:\Windows\system32\AuthFWWizFwk.dll
 C:\Windows\system32\authui.dll
 C:\Windows\system32\authz.dll
 C:\Windows\system32\autochk.exe
 C:\Windows\system32\autoconv.exe
 C:\Windows\system32\autoexec.nt
 C:\Windows\system32\autofmt.exe
 C:\Windows\system32\autoplay.dll
 C:\Windows\system32\AuxiliaryDisplayApi.dll
 C:\Windows\system32\AuxiliaryDisplayClassInstaller.dll
 C:\Windows\system32\AuxiliaryDisplayCpl.dll
 C:\Windows\system32\AuxiliaryDisplayDriverLib.dll
 C:\Windows\system32\AuxiliaryDisplayServices.dll
 C:\Windows\system32\AvastSS.scr
 C:\Windows\system32\avgrsstx.dll.old
 C:\Windows\system32\avicap.dll
 C:\Windows\system32\avicap32.dll
 C:\Windows\system32\avifil32.dll
 C:\Windows\system32\avifile.dll
 C:\Windows\system32\avrt.dll
 C:\Windows\system32\axaltocm.dll
 C:\Windows\system32\azman.msc
 C:\Windows\system32\azroles.dll
 C:\Windows\system32\azroleui.dll
 C:\Windows\system32\AzSqlExt.dll
 C:\Windows\system32\basecsp.dll
 C:\Windows\system32\basesrv.dll
 C:\Windows\system32\batmeter.dll
 C:\Windows\system32\batt.dll
 C:\Windows\system32\bcdedit.exe
 C:\Windows\system32\bcdprov.dll
 C:\Windows\system32\bcdsrv.dll
 C:\Windows\system32\bcrypt.dll
 C:\Windows\system32\bdaplgin.ax
 C:\Windows\system32\BFE.DLL
 C:\Windows\system32\bidispl.dll
 C:\Windows\system32\bios1.rom
 C:\Windows\system32\bios4.rom
 C:\Windows\system32\BitLockerWizard.exe
 C:\Windows\system32\bitsadmin.exe
 C:\Windows\system32\bitsigd.dll
 C:\Windows\system32\bitsperf.dll
 C:\Windows\system32\bitsprx2.dll
 C:\Windows\system32\bitsprx3.dll
 C:\Windows\system32\bitsprx4.dll
 C:\Windows\system32\bitsprx5.dll
 C:\Windows\system32\blackbox.dll
 C:\Windows\system32\BlbEvents.dll
 C:\Windows\system32\blbres.dll
 C:\Windows\system32\blb_ps.dll
 C:\Windows\system32\bootcfg.exe
 C:\Windows\system32\bootstr.dll
 C:\Windows\system32\BOOTVID.DLL
 C:\Windows\system32\bopomofo.uce
 C:\Windows\system32\brcoinst.dll
 C:\Windows\system32\brcpl.dll
 C:\Windows\system32\brcplsdw.dll
 C:\Windows\system32\brcplsiw.dll
 C:\Windows\system32\brdgcfg.dll
 C:\Windows\system32\bridgeres.dll
 C:\Windows\system32\bridgeunattend.exe
 C:\Windows\system32\browser.dll
 C:\Windows\system32\browseui.dll
 C:\Windows\system32\bthci.dll
 C:\Windows\system32\bthprops.cpl
 C:\Windows\system32\bthserv.dll
 C:\Windows\system32\bthudtask.exe
 C:\Windows\system32\btpanui.dll
 C:\Windows\system32\Bubbles.scr
 C:\Windows\system32\cabinet.dll
 C:\Windows\system32\cabview.dll
 C:\Windows\system32\cacls.exe
 C:\Windows\system32\calc.exe
 C:\Windows\system32\capisp.dll
 C:\Windows\system32\CardGames.dll
 C:\Windows\system32\catsrv.dll
 C:\Windows\system32\catsrvps.dll
 C:\Windows\system32\catsrvut.dll
 C:\Windows\system32\cbsra.exe
 C:\Windows\system32\cdd.dll
 C:\Windows\system32\cdosys.dll
 C:\Windows\system32\cero.rs
 C:\Windows\system32\certcli.dll
 C:\Windows\system32\certenc.dll
 C:\Windows\system32\CertEnroll.dll
 C:\Windows\system32\CertEnrollCtrl.exe
 C:\Windows\system32\CertEnrollUI.dll
 C:\Windows\system32\certmgr.dll
 C:\Windows\system32\certmgr.msc
 C:\Windows\system32\certprop.dll
 C:\Windows\system32\certreq.exe
 C:\Windows\system32\certutil.exe
 C:\Windows\system32\cewmdm.dll
 C:\Windows\system32\cfgbkend.dll
 C:\Windows\system32\cfgmgr32.dll
 C:\Windows\system32\chajei.ime
 C:\Windows\system32\change.exe
 C:\Windows\system32\charmap.exe
 C:\Windows\system32\chcp.com
 C:\Windows\system32\chglogon.exe
 C:\Windows\system32\chgport.exe
 C:\Windows\system32\chgusr.exe
 C:\Windows\system32\chkdsk.exe
 C:\Windows\system32\chkntfs.exe
 C:\Windows\system32\choice.exe
 C:\Windows\system32\chsbrkr.dll
 C:\Windows\system32\chtbrkr.dll
 C:\Windows\system32\CHxReadingStringIME.dll
 C:\Windows\system32\ci.dll
 C:\Windows\system32\CIADMIN.DLL
 C:\Windows\system32\CIADV.MSC
 C:\Windows\system32\cic.dll
 C:\Windows\system32\CIDAEMON.EXE
 C:\Windows\system32\cintlgnt.ime
 C:\Windows\system32\ciodm.dll
 C:\Windows\system32\cipher.exe
 C:\Windows\system32\CIRCoInst.dll
 C:\Windows\system32\CISVC.EXE
 C:\Windows\system32\clb.dll
 C:\Windows\system32\clbcatq.dll
 C:\Windows\system32\cleanmgr.exe
 C:\Windows\system32\clfs.sys
 C:\Windows\system32\clfsw32.dll
 C:\Windows\system32\cliconfg.dll
 C:\Windows\system32\cliconfg.exe
 C:\Windows\system32\cliconfg.rll
 C:\Windows\system32\clip.exe
 C:\Windows\system32\clusapi.dll
 C:\Windows\system32\cmcfg32.dll
 C:\Windows\system32\cmd.exe
 C:\Windows\system32\cmdial32.dll
 C:\Windows\system32\CMDIALOG.SRG
 C:\Windows\system32\cmdkey.exe
 C:\Windows\system32\cmdl32.exe
 C:\Windows\system32\cmicryptinstall.dll
 C:\Windows\system32\cmifw.dll
 C:\Windows\system32\cmipnpinstall.dll
 C:\Windows\system32\cmlua.dll
 C:\Windows\system32\cmmon32.exe
 C:\Windows\system32\cmpbk32.dll
 C:\Windows\system32\cmstp.exe
 C:\Windows\system32\cmstplua.dll
 C:\Windows\system32\cmutil.dll
 C:\Windows\system32\cngaudit.dll
 C:\Windows\system32\cnvfat.dll
 C:\Windows\system32\cofire.exe
 C:\Windows\system32\cofiredm.dll
 C:\Windows\system32\colbact.dll
 C:\Windows\system32\collab.cpl
 C:\Windows\system32\COLORCNV.DLL
 C:\Windows\system32\colorcpl.exe
 C:\Windows\system32\colorui.dll
 C:\Windows\system32\comcat.dll
 C:\Windows\system32\COMCT232.DEP
 C:\Windows\system32\COMCT232.oca
 C:\Windows\system32\COMCT232.OCX
 C:\Windows\system32\COMCT332.DEP
 C:\Windows\system32\COMCT332.oca
 C:\Windows\system32\COMCT332.OCX
 C:\Windows\system32\COMCT332.SRG
 C:\Windows\system32\COMCTL.SRG
 C:\Windows\system32\COMCTL2.SRG
 C:\Windows\system32\COMCTL32.DEP
 C:\Windows\system32\comctl32.dll
 C:\Windows\system32\COMCTL32.OCX
 C:\Windows\system32\COMDLG32.DEP
 C:\Windows\system32\comdlg32.dll
 C:\Windows\system32\COMDLG32.oca
 C:\Windows\system32\COMDLG32.OCX
 C:\Windows\system32\comexp.msc
 C:\Windows\system32\COMM.drv
 C:\Windows\system32\COMMAND.COM
 C:\Windows\system32\COMMDLG.DLL
 C:\Windows\system32\COMMTB32.DLL
 C:\Windows\system32\comp.exe
 C:\Windows\system32\compact.exe
 C:\Windows\system32\CompatUI.dll
 C:\Windows\system32\compmgmt.msc
 C:\Windows\system32\CompMgmtLauncher.exe
 C:\Windows\system32\compobj.dll
 C:\Windows\system32\compstui.dll
 C:\Windows\system32\ComputerDefaults.exe
 C:\Windows\system32\comrepl.dll
 C:\Windows\system32\comres.dll
 C:\Windows\system32\comsnap.dll
 C:\Windows\system32\comsvcs.dll
 C:\Windows\system32\comuid.dll
 C:\Windows\system32\config.nt
 C:\Windows\system32\conime.exe
 C:\Windows\system32\connect.dll
 C:\Windows\system32\consent.exe
 C:\Windows\system32\console.dll
 C:\Windows\system32\control.exe
 C:\Windows\system32\convert.exe
 C:\Windows\system32\corpol.dll
 C:\Windows\system32\country.sys
 C:\Windows\system32\CPSOKBTasks.xml
 C:\Windows\system32\credssp.dll
 C:\Windows\system32\credui.dll
 C:\Windows\system32\credwiz.exe
 C:\Windows\system32\CRPPresentation.dll
 C:\Windows\system32\CRSWPP.DLL
 C:\Windows\system32\crtdll.dll
 C:\Windows\system32\crypt32.dll
 C:\Windows\system32\cryptdlg.dll
 C:\Windows\system32\cryptdll.dll
 C:\Windows\system32\cryptext.dll
 C:\Windows\system32\cryptnet.dll
 C:\Windows\system32\cryptsvc.dll
 C:\Windows\system32\cryptui.dll
 C:\Windows\system32\cscapi.dll
 C:\Windows\system32\cscdll.dll
 C:\Windows\system32\CscMig.dll
 C:\Windows\system32\cscobj.dll
 C:\Windows\system32\cscript.exe
 C:\Windows\system32\cscsvc.dll
 C:\Windows\system32\cscui.dll
 C:\Windows\system32\csrsrv.dll
 C:\Windows\system32\csrss.exe
 C:\Windows\system32\csrstub.exe
 C:\Windows\system32\ctfmon.exe
 C:\Windows\system32\ctl3d32.dll
 C:\Windows\system32\ctl3dv2.dll
 C:\Windows\system32\C_037.NLS
 C:\Windows\system32\C_10000.NLS
 C:\Windows\system32\C_10001.NLS
 C:\Windows\system32\C_10002.NLS
 C:\Windows\system32\C_10003.NLS
 C:\Windows\system32\C_10004.NLS
 C:\Windows\system32\C_10005.NLS
 C:\Windows\system32\C_10006.NLS
 C:\Windows\system32\C_10007.NLS
 C:\Windows\system32\C_10008.NLS
 C:\Windows\system32\C_10010.NLS
 C:\Windows\system32\C_10017.NLS
 C:\Windows\system32\C_10021.NLS
 C:\Windows\system32\C_10029.NLS
 C:\Windows\system32\C_10079.NLS
 C:\Windows\system32\C_10081.NLS
 C:\Windows\system32\C_10082.NLS
 C:\Windows\system32\C_1026.NLS
 C:\Windows\system32\C_1047.NLS
 C:\Windows\system32\C_1140.NLS
 C:\Windows\system32\C_1141.NLS
 C:\Windows\system32\C_1142.NLS
 C:\Windows\system32\C_1143.NLS
 C:\Windows\system32\C_1144.NLS
 C:\Windows\system32\C_1145.NLS
 C:\Windows\system32\C_1146.NLS
 C:\Windows\system32\C_1147.NLS
 C:\Windows\system32\C_1148.NLS
 C:\Windows\system32\C_1149.NLS
 C:\Windows\system32\C_1250.NLS
 C:\Windows\system32\C_1251.NLS
 C:\Windows\system32\C_1252.NLS
 C:\Windows\system32\C_1253.NLS
 C:\Windows\system32\C_1254.NLS
 C:\Windows\system32\C_1255.NLS
 C:\Windows\system32\C_1256.NLS
 C:\Windows\system32\C_1257.NLS
 C:\Windows\system32\C_1258.NLS
 C:\Windows\system32\C_1361.NLS
 C:\Windows\system32\C_20000.NLS
 C:\Windows\system32\C_20001.NLS
 C:\Windows\system32\C_20002.NLS
 C:\Windows\system32\C_20003.NLS
 C:\Windows\system32\C_20004.NLS
 C:\Windows\system32\C_20005.NLS
 C:\Windows\system32\C_20105.NLS
 C:\Windows\system32\C_20106.NLS
 C:\Windows\system32\C_20107.NLS
 C:\Windows\system32\C_20108.NLS
 C:\Windows\system32\C_20127.NLS
 C:\Windows\system32\C_20261.NLS
 C:\Windows\system32\C_20269.NLS
 C:\Windows\system32\C_20273.NLS
 C:\Windows\system32\C_20277.NLS
 C:\Windows\system32\C_20278.NLS
 C:\Windows\system32\C_20280.NLS
 C:\Windows\system32\C_20284.NLS
 C:\Windows\system32\C_20285.NLS
 C:\Windows\system32\C_20290.NLS
 C:\Windows\system32\C_20297.NLS
 C:\Windows\system32\C_20420.NLS
 C:\Windows\system32\C_20423.NLS
 C:\Windows\system32\C_20424.NLS
 C:\Windows\system32\C_20833.NLS
 C:\Windows\system32\C_20838.NLS
 C:\Windows\system32\C_20866.NLS
 C:\Windows\system32\C_20871.NLS
 C:\Windows\system32\C_20880.NLS
 C:\Windows\system32\C_20905.NLS
 C:\Windows\system32\C_20924.NLS
 C:\Windows\system32\C_20932.NLS
 C:\Windows\system32\C_20936.NLS
 C:\Windows\system32\C_20949.NLS
 C:\Windows\system32\C_21025.NLS
 C:\Windows\system32\C_21027.NLS
 C:\Windows\system32\C_21866.NLS
 C:\Windows\system32\C_28591.NLS
 C:\Windows\system32\C_28592.NLS
 C:\Windows\system32\C_28593.NLS
 C:\Windows\system32\C_28594.NLS
 C:\Windows\system32\C_28595.NLS
 C:\Windows\system32\C_28596.NLS
 C:\Windows\system32\C_28597.NLS
 C:\Windows\system32\C_28598.NLS
 C:\Windows\system32\C_28599.NLS
 C:\Windows\system32\c_28603.nls
 C:\Windows\system32\C_28605.NLS
 C:\Windows\system32\C_437.NLS
 C:\Windows\system32\C_500.NLS
 C:\Windows\system32\C_708.NLS
 C:\Windows\system32\C_720.NLS
 C:\Windows\system32\C_737.NLS
 C:\Windows\system32\C_775.NLS
 C:\Windows\system32\C_850.NLS
 C:\Windows\system32\C_852.NLS
 C:\Windows\system32\C_855.NLS
 C:\Windows\system32\C_857.NLS
 C:\Windows\system32\C_858.NLS
 C:\Windows\system32\C_860.NLS
 C:\Windows\system32\C_861.NLS
 C:\Windows\system32\C_862.NLS
 C:\Windows\system32\C_863.NLS
 C:\Windows\system32\C_864.NLS
 C:\Windows\system32\C_865.NLS
 C:\Windows\system32\C_866.NLS
 C:\Windows\system32\C_869.NLS
 C:\Windows\system32\C_870.NLS
 C:\Windows\system32\C_874.NLS
 C:\Windows\system32\C_875.NLS
 C:\Windows\system32\C_932.NLS
 C:\Windows\system32\C_936.NLS
 C:\Windows\system32\C_949.NLS
 C:\Windows\system32\C_950.NLS
 C:\Windows\system32\C_G18030.DLL
 C:\Windows\system32\C_IS2022.DLL
 C:\Windows\system32\C_ISCII.DLL
 C:\Windows\system32\d3d10.dll
 C:\Windows\system32\d3d10core.dll
 C:\Windows\system32\d3d10_1.dll
 C:\Windows\system32\d3d10_1core.dll
 C:\Windows\system32\d3d8.dll
 C:\Windows\system32\d3d8thk.dll
 C:\Windows\system32\d3d9.dll
 C:\Windows\system32\d3dim.dll
 C:\Windows\system32\d3dim700.dll
 C:\Windows\system32\d3dramp.dll
 C:\Windows\system32\d3dxof.dll
 C:\Windows\system32\dataclen.dll
 C:\Windows\system32\DATALIST.SRG
 C:\Windows\system32\davclnt.dll
 C:\Windows\system32\DBADAPT.DLL
 C:\Windows\system32\dbgeng.dll
 C:\Windows\system32\dbghelp.dll
 C:\Windows\system32\DBGRID.SRG
 C:\Windows\system32\DBGRID32.DEP
 C:\Windows\system32\DBGRID32.OCX
 C:\Windows\system32\DBLIST.SRG
 C:\Windows\system32\DBLIST32.DEP
 C:\Windows\system32\DBLIST32.OCX
 C:\Windows\system32\DBMSSHRN.DLL
 C:\Windows\system32\DBMSSOCN.DLL
 C:\Windows\system32\dbnetlib.dll
 C:\Windows\system32\dbnmpntw.dll
 C:\Windows\system32\dciman32.dll
 C:\Windows\system32\dcomcnfg.exe
 C:\Windows\system32\DDACLSys.dll
 C:\Windows\system32\DDEML.DLL
 C:\Windows\system32\ddraw.dll
 C:\Windows\system32\ddrawex.dll
 C:\Windows\system32\debug.exe
 C:\Windows\system32\Defrag.exe
 C:\Windows\system32\desk.cpl
 C:\Windows\system32\deskadp.dll
 C:\Windows\system32\deskmon.dll
 C:\Windows\system32\deskperf.dll
 C:\Windows\system32\desktop.ini
 C:\Windows\system32\devenum.dll
 C:\Windows\system32\DeviceEject.exe
 C:\Windows\system32\DeviceProperties.exe
 C:\Windows\system32\devmgmt.msc
 C:\Windows\system32\devmgr.dll
 C:\Windows\system32\DEVTLDC.DLL
 C:\Windows\system32\dfdts.dll
 C:\Windows\system32\DFDWiz.exe
 C:\Windows\system32\dfrgfat.exe
 C:\Windows\system32\dfrgifc.exe
 C:\Windows\system32\dfrgifps.dll
 C:\Windows\system32\DfrgNtfs.exe
 C:\Windows\system32\DfrgRes.dll
 C:\Windows\system32\dfrgui.exe
 C:\Windows\system32\dfshim.dll
 C:\Windows\system32\dfsr.exe
 C:\Windows\system32\dfsrres.dll
 C:\Windows\system32\DfsShlEx.dll
 C:\Windows\system32\dhcpcmonitor.dll
 C:\Windows\system32\dhcpcsvc.dll
 C:\Windows\system32\dhcpcsvc6.dll
 C:\Windows\system32\DHCPQEC.DLL
 C:\Windows\system32\dhcpsapi.dll
 C:\Windows\system32\dhcpsoc.dll
 C:\Windows\system32\diagperf.dll
 C:\Windows\system32\dialer.exe
 C:\Windows\system32\diantz.exe
 C:\Windows\system32\dimsjob.dll
 C:\Windows\system32\dimsroam.dll
 C:\Windows\system32\dinput.dll
 C:\Windows\system32\dinput8.dll
 C:\Windows\system32\diskcomp.com
 C:\Windows\system32\diskcopy.com
 C:\Windows\system32\diskcopy.dll
 C:\Windows\system32\diskmgmt.msc
 C:\Windows\system32\diskpart.exe
 C:\Windows\system32\diskperf.exe
 C:\Windows\system32\diskraid.exe
 C:\Windows\system32\dispci.dll
 C:\Windows\system32\dispdiag.exe
 C:\Windows\system32\dispex.dll
 C:\Windows\system32\dllhost.exe
 C:\Windows\system32\dllhst3g.exe
 C:\Windows\system32\dmband.dll
 C:\Windows\system32\dmcompos.dll
 C:\Windows\system32\dmdlgs.dll
 C:\Windows\system32\dmdskmgr.dll
 C:\Windows\system32\dmdskres.dll
 C:\Windows\system32\dmdskres2.dll
 C:\Windows\system32\dmime.dll
 C:\Windows\system32\dmintf.dll
 C:\Windows\system32\dmloader.dll
 C:\Windows\system32\dmocx.dll
 C:\Windows\system32\dmscript.dll
 C:\Windows\system32\dmstyle.dll
 C:\Windows\system32\dmsynth.dll
 C:\Windows\system32\dmusic.dll
 C:\Windows\system32\dmutil.dll
 C:\Windows\system32\dmvdsitf.dll
 C:\Windows\system32\dmview.ocx
 C:\Windows\system32\dnsapi.dll
 C:\Windows\system32\dnscacheugc.exe
 C:\Windows\system32\dnshc.dll
 C:\Windows\system32\dnsrslvr.dll
 C:\Windows\system32\docprop.dll
 C:\Windows\system32\doskey.exe
 C:\Windows\system32\dosx.exe
 C:\Windows\system32\dot3.tmf
 C:\Windows\system32\dot3api.dll
 C:\Windows\system32\dot3cfg.dll
 C:\Windows\system32\dot3dlg.dll
 C:\Windows\system32\dot3gpclnt.dll
 C:\Windows\system32\dot3gpui.dll
 C:\Windows\system32\dot3msm.dll
 C:\Windows\system32\dot3svc.dll
 C:\Windows\system32\dot3ui.dll
 C:\Windows\system32\dpapimig.exe
 C:\Windows\system32\dpinst.exe
 C:\Windows\system32\DpiScaling.exe
 C:\Windows\system32\dplaysvr.exe
 C:\Windows\system32\dplayx.dll
 C:\Windows\system32\dpmodemx.dll
 C:\Windows\system32\dpnaddr.dll
 C:\Windows\system32\dpnathlp.dll
 C:\Windows\system32\dpnet.dll
 C:\Windows\system32\dpnhpast.dll
 C:\Windows\system32\dpnhupnp.dll
 C:\Windows\system32\dpnlobby.dll
 C:\Windows\system32\dpnsvr.exe
 C:\Windows\system32\dps.dll
 C:\Windows\system32\dpwsockx.dll
 C:\Windows\system32\dpx.dll
 C:\Windows\system32\driverquery.exe
 C:\Windows\system32\drmmgrtn.dll
 C:\Windows\system32\drmv2clt.dll
 C:\Windows\system32\drprov.dll
 C:\Windows\system32\drvinst.exe
 C:\Windows\system32\drvstore.dll
 C:\Windows\system32\DRWATSON.EXE
 C:\Windows\system32\ds16gt.dLL
 C:\Windows\system32\ds32gt.dll
 C:\Windows\system32\dsauth.dll
 C:\Windows\system32\dsdmo.dll
 C:\Windows\system32\dskquota.dll
 C:\Windows\system32\dskquoui.dll
 C:\Windows\system32\dsound.dll
 C:\Windows\system32\dsprop.dll
 C:\Windows\system32\dsquery.dll
 C:\Windows\system32\dssec.dat
 C:\Windows\system32\dssec.dll
 C:\Windows\system32\dssenh.dll
 C:\Windows\system32\dsuiext.dll
 C:\Windows\system32\dswave.dll
 C:\Windows\system32\dtsh.dll
 C:\Windows\system32\duser.dll
 C:\Windows\system32\dvdplay.exe
 C:\Windows\system32\dvdupgrd.exe
 C:\Windows\system32\dwm.exe
 C:\Windows\system32\dwmapi.dll
 C:\Windows\system32\dwmredir.dll
 C:\Windows\system32\DWWIN.EXE
 C:\Windows\system32\dx3j.dll
 C:\Windows\system32\dxdiag.exe
 C:\Windows\system32\dxdiagn.dll
 C:\Windows\system32\dxgi.dll
 C:\Windows\system32\dxmasf.dll
 C:\Windows\system32\dxtmsft.dll
 C:\Windows\system32\dxtrans.dll
 C:\Windows\system32\dxva2.dll
 C:\Windows\system32\eaphost.tmf
 C:\Windows\system32\eapp3hst.dll
 C:\Windows\system32\eappcfg.dll
 C:\Windows\system32\eappgnui.dll
 C:\Windows\system32\eapphost.dll
 C:\Windows\system32\eappprxy.dll
 C:\Windows\system32\EAPQEC.DLL
 C:\Windows\system32\eapsvc.dll
 C:\Windows\system32\edit.com
 C:\Windows\system32\EDIT.HLP
 C:\Windows\system32\edlin.exe
 C:\Windows\system32\efsadu.dll
 C:\Windows\system32\efsui.exe
 C:\Windows\system32\ega.cpi
 C:\Windows\system32\els.dll
 C:\Windows\system32\emdmgmt.dll
 C:\Windows\system32\emptyregdb.dat
 C:\Windows\system32\encapi.dll
 C:\Windows\system32\EncDec.dll
 C:\Windows\system32\EncDump.dll
 C:\Windows\system32\eqossnap.dll
 C:\Windows\system32\es.dll
 C:\Windows\system32\esent.dll
 C:\Windows\system32\esentprf.dll
 C:\Windows\system32\esentutl.exe
 C:\Windows\system32\esrb.rs
 C:\Windows\system32\eudcedit.exe
 C:\Windows\system32\EULA.Microsoft.Application.Verifier.rtf
 C:\Windows\system32\eventcls.dll
 C:\Windows\system32\eventcreate.exe
 C:\Windows\system32\EventViewer_EventDetails.xsl
 C:\Windows\system32\eventvwr.exe
 C:\Windows\system32\eventvwr.msc
 C:\Windows\system32\evr.dll
 C:\Windows\system32\exe2bin.exe
 C:\Windows\system32\expand.exe
 C:\Windows\system32\ExplorerFrame.dll
 C:\Windows\system32\expsrv.dll
 C:\Windows\system32\extmgr.dll
 C:\Windows\system32\extrac32.exe
 C:\Windows\system32\f3ahvoas.dll
 C:\Windows\system32\fastopen.exe
 C:\Windows\system32\Faultrep.dll
 C:\Windows\system32\fc.exe
 C:\Windows\system32\fde.dll
 C:\Windows\system32\fdeploy.dll
 C:\Windows\system32\fdPHost.dll
 C:\Windows\system32\fdProxy.dll
 C:\Windows\system32\FDResPub.dll
 C:\Windows\system32\fdSSDP.dll
 C:\Windows\system32\fdWCN.dll
 C:\Windows\system32\fdWNet.dll
 C:\Windows\system32\fdWSD.dll
 C:\Windows\system32\feclient.dll
 C:\Windows\system32\filemgmt.dll
 C:\Windows\system32\find.exe
 C:\Windows\system32\findnetprinters.dll
 C:\Windows\system32\findstr.exe
 C:\Windows\system32\finger.exe
 C:\Windows\system32\Firewall.cpl
 C:\Windows\system32\FirewallAPI.dll
 C:\Windows\system32\FirewallControlPanel.exe
 C:\Windows\system32\FirewallSettings.exe
 C:\Windows\system32\fixmapi.exe
 C:\Windows\system32\Flash8.oca
 C:\Windows\system32\Flash8.ocx
 C:\Windows\system32\fltLib.dll
 C:\Windows\system32\fltMC.exe
 C:\Windows\system32\FlyTreeXCtrl.oca
 C:\Windows\system32\FlyTreeXCtrl.ocx
 C:\Windows\system32\FM20.DLL
 C:\Windows\system32\FM20ENU.DLL
 C:\Windows\system32\fmifs.dll
 C:\Windows\system32\FNTCACHE.DAT
 C:\Windows\system32\fontext.dll
 C:\Windows\system32\fontsub.dll
 C:\Windows\system32\fontview.exe
 C:\Windows\system32\forfiles.exe
 C:\Windows\system32\format.com
 C:\Windows\system32\fphc.dll
 C:\Windows\system32\FPWPP.DLL
 C:\Windows\system32\framebuf.dll
 C:\Windows\system32\framedyn.dll
 C:\Windows\system32\framedynos.dll
 C:\Windows\system32\fsmgmt.msc
 C:\Windows\system32\fsutil.exe
 C:\Windows\system32\ftlx0411.dll
 C:\Windows\system32\ftlx041e.dll
 C:\Windows\system32\ftp.exe
 C:\Windows\system32\FTPWPP.DLL
 C:\Windows\system32\ftsrch.dll
 C:\Windows\system32\fundisc.dll
 C:\Windows\system32\fveapi.dll
 C:\Windows\system32\fvecpl.dll
 C:\Windows\system32\fvenotify.exe
 C:\Windows\system32\fveRecover.dll
 C:\Windows\system32\fveui.dll
 C:\Windows\system32\fwcfg.dll
 C:\Windows\system32\FWPUCLNT.DLL
 C:\Windows\system32\FwRemoteSvr.dll
 C:\Windows\system32\FXSAPI.dll
 C:\Windows\system32\FXSCOM.dll
 C:\Windows\system32\FXSCOMEX.dll
 C:\Windows\system32\FXSCOMPOSE.dll
 C:\Windows\system32\FXSCOMPOSERES.dll
 C:\Windows\system32\FXSCOVER.exe
 C:\Windows\system32\FXSEVENT.dll
 C:\Windows\system32\FXSEXT32.dll
 C:\Windows\system32\FXSMON.dll
 C:\Windows\system32\FXSRESM.dll
 C:\Windows\system32\FXSROUTE.dll
 C:\Windows\system32\FXSST.dll
 C:\Windows\system32\FXSSVC.exe
 C:\Windows\system32\FXST30.dll
 C:\Windows\system32\FXSTIFF.dll
 C:\Windows\system32\FXSUNATD.exe
 C:\Windows\system32\FXSUTILITY.dll
 C:\Windows\system32\FXSXP32.dll
 C:\Windows\system32\g711codc.ax
 C:\Windows\system32\gacinstall.dll
 C:\Windows\system32\gameux.dll
 C:\Windows\system32\GameUXLegacyGDFs.dll
 C:\Windows\system32\gatherWiredInfo.vbs
 C:\Windows\system32\gatherWiredInfo.xslt
 C:\Windows\system32\gatherWirelessInfo.vbs
 C:\Windows\system32\gatherWirelessInfo.xslt
 C:\Windows\system32\gb2312.uce
 C:\Windows\system32\gcdef.dll
 C:\Windows\system32\GDI.EXE
 C:\Windows\system32\gdi32.dll
 C:\Windows\system32\getmac.exe
 C:\Windows\system32\getuname.dll
 C:\Windows\system32\GflAx.dll
 C:\Windows\system32\glmf32.dll
 C:\Windows\system32\glu32.dll
 C:\Windows\system32\gpapi.dll
 C:\Windows\system32\gpedit.dll
 C:\Windows\system32\gpedit.msc
 C:\Windows\system32\gpprefcl.dll
 C:\Windows\system32\gpprnext.dll
 C:\Windows\system32\gpresult.exe
 C:\Windows\system32\gpscript.dll
 C:\Windows\system32\gpscript.exe
 C:\Windows\system32\gpsvc.dll
 C:\Windows\system32\gptext.dll
 C:\Windows\system32\gpupdate.exe
 C:\Windows\system32\graftabl.com
 C:\Windows\system32\GRAPHICS.COM
 C:\Windows\system32\graphics.pro
 C:\Windows\system32\grb.rs
 C:\Windows\system32\grpconv.exe
 C:\Windows\system32\GuidedHelp.dll
 C:\Windows\system32\hal.dll
 C:\Windows\system32\halacpi.dll
 C:\Windows\system32\halmacpi.dll
 C:\Windows\system32\hbaapi.dll
 C:\Windows\system32\hccoin.dll
 C:\Windows\system32\hcrstco.dll
 C:\Windows\system32\hdwwiz.cpl
 C:\Windows\system32\hdwwiz.exe
 C:\Windows\system32\help.exe
 C:\Windows\system32\HelpPaneProxy.dll
 C:\Windows\system32\hha.dll
 C:\Windows\system32\hhctrl.ocx
 C:\Windows\system32\hhsetup.dll
 C:\Windows\system32\hid.dll
 C:\Windows\system32\hidphone.tsp
 C:\Windows\system32\hidserv.dll
 C:\Windows\system32\HIMEM.SYS
 C:\Windows\system32\hlink.dll
 C:\Windows\system32\HLP95EN.DLL
 C:\Windows\system32\hnetcfg.dll
 C:\Windows\system32\hnetmon.dll
 C:\Windows\system32\HOSTNAME.EXE
 C:\Windows\system32\hotplug.dll
 C:\Windows\system32\HotStartUserAgent.dll
 C:\Windows\system32\hpotscl1.dll
 C:\Windows\system32\hpowiav1.dll
 C:\Windows\system32\HPZLLLHN.DLL
 C:\Windows\system32\html.iec
 C:\Windows\system32\HTMUTIL.DLL
 C:\Windows\system32\httpapi.dll
 C:\Windows\system32\htui.dll
 C:\Windows\system32\iac25_32.ax
 C:\Windows\system32\ias.dll
 C:\Windows\system32\iasacct.dll
 C:\Windows\system32\iasads.dll
 C:\Windows\system32\iasdatastore.dll
 C:\Windows\system32\iashlpr.dll
 C:\Windows\system32\iashost.exe
 C:\Windows\system32\IasMigPlugin.dll
 C:\Windows\system32\iasnap.dll
 C:\Windows\system32\iaspolcy.dll
 C:\Windows\system32\iasrad.dll
 C:\Windows\system32\iasrecst.dll
 C:\Windows\system32\iassam.dll
 C:\Windows\system32\iassdo.dll
 C:\Windows\system32\iassvcs.dll
 C:\Windows\system32\icaapi.dll
 C:\Windows\system32\icacls.exe
 C:\Windows\system32\icardagt.exe
 C:\Windows\system32\icardie.dll
 C:\Windows\system32\icardres.dll
 C:\Windows\system32\iccvid.dll
 C:\Windows\system32\icfupgd.dll
 C:\Windows\system32\icm32.dll
 C:\Windows\system32\icmp.dll
 C:\Windows\system32\icmui.dll
 C:\Windows\system32\IconCodecService.dll
 C:\Windows\system32\icrav03.rat
 C:\Windows\system32\icsfiltr.dll
 C:\Windows\system32\icsigd.dll
 C:\Windows\system32\icsunattend.exe
 C:\Windows\system32\ideograf.uce
 C:\Windows\system32\idndl.dll
 C:\Windows\system32\idq.dll
 C:\Windows\system32\ie4uinit.exe
 C:\Windows\system32\ieakeng.dll
 C:\Windows\system32\ieaksie.dll
 C:\Windows\system32\ieakui.dll
 C:\Windows\system32\ieapfltr.dat
 C:\Windows\system32\ieapfltr.dll
 C:\Windows\system32\iedkcs32.dll
 C:\Windows\system32\ieencode.dll
 C:\Windows\system32\ieframe.dll
 C:\Windows\system32\ieframe.oca
 C:\Windows\system32\iepeers.dll
 C:\Windows\system32\iernonce.dll
 C:\Windows\system32\iertutil.dll
 C:\Windows\system32\iesetup.dll
 C:\Windows\system32\ieui.dll
 C:\Windows\system32\ieuinit.inf
 C:\Windows\system32\ieUnatt.exe
 C:\Windows\system32\iexpress.exe
 C:\Windows\system32\ifmon.dll
 C:\Windows\system32\ifsutil.dll
 C:\Windows\system32\ifsutilx.dll
 C:\Windows\system32\ifxcardm.dll
 C:\Windows\system32\IKEEXT.DLL
 C:\Windows\system32\imaadp32.acm
 C:\Windows\system32\imagehlp.dll
 C:\Windows\system32\imageres.dll
 C:\Windows\system32\imagesp1.dll
 C:\Windows\system32\imapi.dll
 C:\Windows\system32\imapi2.dll
 C:\Windows\system32\imapi2fs.dll
 C:\Windows\system32\imgutil.dll
 C:\Windows\system32\IMGWALK.DLL
 C:\Windows\system32\IMJP10.IME
 C:\Windows\system32\IMJP10K.DLL
 C:\Windows\system32\imkr80.ime
 C:\Windows\system32\imm32.dll
 C:\Windows\system32\inetcomm.dll
 C:\Windows\system32\inetcpl.cpl
 C:\Windows\system32\INETCTLS.SRG
 C:\Windows\system32\inetmib1.dll
 C:\Windows\system32\inetpp.dll
 C:\Windows\system32\inetppui.dll
 C:\Windows\system32\INETRES.dll
 C:\Windows\system32\InfDefaultInstall.exe
 C:\Windows\system32\infocardapi.dll
 C:\Windows\system32\infocardcpl.cpl
 C:\Windows\system32\InkEd.dll
 C:\Windows\system32\input.dll
 C:\Windows\system32\inseng.dll
 C:\Windows\system32\INSTCAT.SQL
 C:\Windows\system32\intl.cpl
 C:\Windows\system32\iologmsg.dll
 C:\Windows\system32\IPBusEnum.dll
 C:\Windows\system32\IPBusEnumProxy.dll
 C:\Windows\system32\ipconfig.exe
 C:\Windows\system32\IPHLPAPI.DLL
 C:\Windows\system32\iphlpsvc.dll
 C:\Windows\system32\ipnathlp.dll
 C:\Windows\system32\iprop.dll
 C:\Windows\system32\iprtprio.dll
 C:\Windows\system32\iprtrmgr.dll
 C:\Windows\system32\ipsecsnp.dll
 C:\Windows\system32\IPSECSVC.DLL
 C:\Windows\system32\ipsmsnap.dll
 C:\Windows\system32\ir32_32.dll
 C:\Windows\system32\ir41_32.ax
 C:\Windows\system32\ir41_qc.dll
 C:\Windows\system32\ir41_qcx.dll
 C:\Windows\system32\ir50_32.dll
 C:\Windows\system32\ir50_qc.dll
 C:\Windows\system32\ir50_qcx.dll
 C:\Windows\system32\irclass.dll
 C:\Windows\system32\irftp.exe
 C:\Windows\system32\irmon.dll
 C:\Windows\system32\irprops.cpl
 C:\Windows\system32\iscsicli.exe
 C:\Windows\system32\iscsicpl.dll
 C:\Windows\system32\iscsicpl.exe
 C:\Windows\system32\iscsidsc.dll
 C:\Windows\system32\iscsied.dll
 C:\Windows\system32\iscsiexe.dll
 C:\Windows\system32\iscsilog.dll
 C:\Windows\system32\iscsium.dll
 C:\Windows\system32\iscsiwmi.dll
 C:\Windows\system32\isintsup.exe
 C:\Windows\system32\itircl.dll
 C:\Windows\system32\itss.dll
 C:\Windows\system32\ivfsrc.ax
 C:\Windows\system32\ixsso.dll
 C:\Windows\system32\iyuv_32.dll
 C:\Windows\system32\java.exe
 C:\Windows\system32\javacypt.dll
 C:\Windows\system32\javaee.dll
 C:\Windows\system32\javaperm.hlp
 C:\Windows\system32\javaprxy.dll
 C:\Windows\system32\javart.dll
 C:\Windows\system32\javasec.hlp
 C:\Windows\system32\javasup.vxd
 C:\Windows\system32\javaw.exe
 C:\Windows\system32\javaws.exe
 C:\Windows\system32\jdbgmgr.exe
 C:\Windows\system32\jit.dll
 C:\Windows\system32\jnwmon.dll
 C:\Windows\system32\joy.cpl
 C:\Windows\system32\jscript.dll
 C:\Windows\system32\jsproxy.dll
 C:\Windows\system32\jupdate-1.6.0_04-b12.log
 C:\Windows\system32\jupdate-1.6.0_06-b02.log
 C:\Windows\system32\kanji_1.uce
 C:\Windows\system32\kanji_2.uce
 C:\Windows\system32\KB16.COM
 C:\Windows\system32\kbd101.dll
 C:\Windows\system32\kbd101a.dll
 C:\Windows\system32\kbd101b.dll
 C:\Windows\system32\kbd101c.dll
 C:\Windows\system32\kbd103.dll
 C:\Windows\system32\kbd106.dll
 C:\Windows\system32\kbd106n.dll
 C:\Windows\system32\KBDA1.DLL
 C:\Windows\system32\KBDA2.DLL
 C:\Windows\system32\KBDA3.DLL
 C:\Windows\system32\KBDAL.DLL
 C:\Windows\system32\KBDARME.DLL
 C:\Windows\system32\KBDARMW.DLL
 C:\Windows\system32\kbdax2.dll
 C:\Windows\system32\KBDAZE.DLL
 C:\Windows\system32\KBDAZEL.DLL
 C:\Windows\system32\KBDBASH.DLL
 C:\Windows\system32\KBDBE.DLL
 C:\Windows\system32\KBDBENE.DLL
 C:\Windows\system32\KBDBGPH.DLL
 C:\Windows\system32\KBDBHC.DLL
 C:\Windows\system32\KBDBLR.DLL
 C:\Windows\system32\KBDBR.DLL
 C:\Windows\system32\KBDBU.DLL
 C:\Windows\system32\KBDBULG.DLL
 C:\Windows\system32\KBDCA.DLL
 C:\Windows\system32\KBDCAN.DLL
 C:\Windows\system32\KBDCR.DLL
 C:\Windows\system32\KBDCZ.DLL
 C:\Windows\system32\KBDCZ1.DLL
 C:\Windows\system32\KBDCZ2.DLL
 C:\Windows\system32\KBDDA.DLL
 C:\Windows\system32\KBDDIV1.DLL
 C:\Windows\system32\KBDDIV2.DLL
 C:\Windows\system32\KBDDV.DLL
 C:\Windows\system32\KBDES.DLL
 C:\Windows\system32\KBDEST.DLL
 C:\Windows\system32\KBDFA.DLL
 C:\Windows\system32\KBDFC.DLL
 C:\Windows\system32\KBDFI.DLL
 C:\Windows\system32\