 run "control.exe" "joy.cpl,Game Controllers"
 run "control.exe" "desk.cpl,Display"
 run "control.exe" "inetcpl.cpl,Internet Options"
 run "control.exe" "appwiz.cpl,Add or Remove Programs"
 run "control.exe" "hdwwiz.cpl,Add Hardware"
 run "control.exe" "intl.cpl,Regional and Language Options"
 run "control.exe" "main.cpl,Mouse"
 run "control.exe" "main.cpl,Keyboard"
 run "control.exe" "mmsys.cpl,Sounds and Audio Devices"
 run "control.exe" "ncpa.cpl,Network Connections"
 run "control.exe" "nusrmgr.cpl,User Accounts"
 run "control.exe" "odbccp32.cpl,Data Sources (ODBC)"
 run "control.exe" "powercfg.cpl"
 run "control.exe" "timedate.cpl,Date and Time"
 run "control.exe" "access.cpl,Accessibility Options"
 run "control.exe" "sysdm.cpl,System"
 run "control.exe" "telephon.cpl,Phone and Modem Options"
 run "control.exe" "TWEAKUI.CPL,Tweak UI"
 run "control.exe" "speech.cpl,Speech"

 run "rundll32.exe" "shell32.dll,Options_RunDLL 0"
 run "rundll32.exe" "shell32.dll,Options_RunDLL 1"
