"$my qm$\a3d_dll_0.ico"
"$qm$\folder.ico"
"&$qm$\folder.ico"
":7 $qm$\folder.ico"
"&:7 $qm$\folder.ico"
"notepad.exe"
"$system$\notepad.exe,0"
"&$system$\notepad.exe,0"
si5="$system$\shell32.dll,8"
si5="q:\my qm\shell32vista.dll,15"
si5="&:7 $my qm$\shell32vista.dll,5"
