ref SCI

int h=GetQmCodeEditor
SendMessage h SCI_SETMARGINMASKN 0 0xFE000000
SendMessage h SCI_SETMARGINTYPEN 0 0
SendMessage h SCI_SETMARGINSENSITIVEN 0 1
SendMessage h SCI_SETMARGINWIDTHN 0 16
SendMessage h SCI_SETPROPERTY "fold" "1"

SendMessage h SCI_MARKERDEFINE SC_MARKNUM_FOLDEROPEN SC_MARK_BOXMINUS
SendMessage h SCI_MARKERDEFINE SC_MARKNUM_FOLDER SC_MARK_BOXPLUS
SendMessage h SCI_MARKERDEFINE SC_MARKNUM_FOLDERSUB SC_MARK_VLINE
SendMessage h SCI_MARKERDEFINE SC_MARKNUM_FOLDERTAIL SC_MARK_LCORNER
SendMessage h SCI_MARKERDEFINE SC_MARKNUM_FOLDEREND SC_MARK_BOXPLUSCONNECTED
SendMessage h SCI_MARKERDEFINE SC_MARKNUM_FOLDEROPENMID SC_MARK_BOXMINUSCONNECTED
SendMessage h SCI_MARKERDEFINE SC_MARKNUM_FOLDERMIDTAIL SC_MARK_TCORNER

int col=0xff8080
SendMessage h SCI_MARKERSETFORE SC_MARKNUM_FOLDEROPEN col
SendMessage h SCI_MARKERSETFORE SC_MARKNUM_FOLDER col
SendMessage h SCI_MARKERSETBACK SC_MARKNUM_FOLDERSUB col
SendMessage h SCI_MARKERSETBACK SC_MARKNUM_FOLDERTAIL col
SendMessage h SCI_MARKERSETFORE SC_MARKNUM_FOLDEREND col
SendMessage h SCI_MARKERSETFORE SC_MARKNUM_FOLDEROPENMID col
SendMessage h SCI_MARKERSETBACK SC_MARKNUM_FOLDERMIDTAIL col

 SendMessage h SCI_MARKERADD 1 SC_MARKNUM_FOLDEROPEN
 SendMessage h SCI_MARKERADD 2 SC_MARKNUM_FOLDER
 SendMessage h SCI_MARKERADD 3 SC_MARKNUM_FOLDERSUB
 SendMessage h SCI_MARKERADD 4 SC_MARKNUM_FOLDERTAIL
 SendMessage h SCI_MARKERADD 5 SC_MARKNUM_FOLDEREND
 SendMessage h SCI_MARKERADD 6 SC_MARKNUM_FOLDEROPENMID
 SendMessage h SCI_MARKERADD 7 SC_MARKNUM_FOLDERMIDTAIL


SendMessage h SCI_SETFOLDLEVEL 10 1|SC_FOLDLEVELHEADERFLAG
SendMessage h SCI_SETFOLDLEVEL 11 1
SendMessage h SCI_SETFOLDLEVEL 12 1

SendMessage h SCI_SETFOLDEXPANDED 10 0
SendMessage h SCI_HIDELINES 11 12
3
SendMessage h SCI_SETFOLDEXPANDED 10 1
SendMessage h SCI_SHOWLINES 11 12

 SendMessage h SCI_TOGGLEFOLD 10 0
 3
 SendMessage h SCI_TOGGLEFOLD 10 0
